#!/usr/bin/env bash
set -euo pipefail

# build.sh — build the AI sandbox image.
#
# Reads sandbox.conf, regenerates the allowlist-*.txt files from the *.d/
# fragment directories, and passes a --build-arg per component to docker build.

_here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=sandbox-common.sh
source "${_here}/sandbox-common.sh"

usage() {
  cat <<'EOF'
Usage:
  ./build.sh [image-name] [--no-cache]

Builds the AI sandbox image (reads sandbox.conf, regenerates allowlists).

Arguments:
  image-name   Optional image tag to build (default: $IMAGE_NAME or ai-sandbox).

Flags:
  --no-cache   Pass --no-cache to docker build (also: NO_CACHE=1 ./build.sh).

Environment variables:
  IMAGE_NAME   Image to build (default: ai-sandbox).
  NO_CACHE     Set to 1 to pass --no-cache to docker build.
  AGENTS_CACHE_BUST
               Opaque token (e.g. a timestamp) that busts the Docker layer cache
               for the agent install layers ONLY (Copilot/Claude/Codex/Gemini/Kiro
               and everything after them), reusing the heavy toolchain layers
               above. Default 0 (cache reused). runme.sh sets a fresh value to
               refresh stale agents quickly; you can also do it manually:
               AGENTS_CACHE_BUST=$(date +%s) ./build.sh
  GITHUB_TOKEN Build-time only. Passed to docker build as a BuildKit secret
               (--secret id=github_token) so install-tools.sh can use the
               authenticated GitHub API (5000 req/h vs 60 req/h). Never written
               into any image layer or visible in `docker history`. If unset,
               GITHUB_PERSONAL_ACCESS_TOKEN is used as a fallback.

Configuration:
  Edit sandbox.conf to enable or disable optional components before building.
EOF
}

# ── Validation ─────────────────────────────────────────────────────────────────

validate_config() {
  if is_enabled copilot && ! is_enabled github-cli; then
    printf 'NOTE: copilot=ON implies github-cli. gh CLI will be installed for authentication.\n' >&2
  fi
  if has_versions rails && ! has_versions ruby; then
    printf 'ERROR: rails is set in sandbox.conf but ruby is empty. Rails requires Ruby (via rvm).\n' >&2
    exit 1
  fi
  local ruby_val; ruby_val=$(get_versions ruby)
  if [[ "$ruby_val" == *,* ]]; then
    printf 'ERROR: ruby only supports a single version (got: "%s").\n' "$ruby_val" >&2
    printf '       Use a single version, e.g.: ruby=3.4.3\n' >&2
    exit 1
  fi
  local rails_val; rails_val=$(get_versions rails)
  if [[ "$rails_val" == *,* ]]; then
    printf 'ERROR: rails only supports a single version (got: "%s").\n' "$rails_val" >&2
    printf '       Use a single version, e.g.: rails=8.0.2\n' >&2
    exit 1
  fi
  local angular_val; angular_val=$(get_versions angular-cli)
  if [[ "$angular_val" == *,* ]]; then
    printf 'ERROR: angular-cli only supports a single version (got: "%s").\n' "$angular_val" >&2
    printf '       Use ON (latest), a single version number (e.g. 19), or OFF.\n' >&2
    exit 1
  fi
  local jvm_key jvm_val ver
  for jvm_key in openjdk graalvm-ce graalvm-oracle kotlin scala maven gradle; do
    jvm_val=$(get_versions "$jvm_key")
    [[ -z "$jvm_val" ]] && continue
    IFS=',' read -ra _vers <<< "$jvm_val"
    for ver in "${_vers[@]}"; do
      ver="${ver// /}"
      if [[ "$ver" != *.* ]]; then
        printf 'ERROR: %s version "%s" looks like a major version only.\n' "$jvm_key" "$ver" >&2
        printf '       SDKMAN requires full patch versions, e.g. 21.0.5 not 21.\n' >&2
        printf '       Run "sdk list java" inside a container to see valid identifiers.\n' >&2
        exit 1
      fi
    done
  done
}

# ── Allowlist generation ─────────────────────────────────────────────────────────

include_fragment() {
  local fragment="$1"
  if [[ -f "$fragment" ]]; then cat "$fragment"; fi
}

include_if_enabled() {
  local fragment="$1"; shift
  if any_enabled "$@"; then
    include_fragment "$fragment"
  fi
}

include_if_has_versions() {
  local fragment="$1"; shift
  if any_has_versions "$@"; then
    include_fragment "$fragment"
  fi
}

generate_allowlists() {
  local domains_d="${script_dir}/allowlist-domains.d"
  local proxy_d="${script_dir}/allowlist-proxy-domains.d"
  local cidrs_d="${script_dir}/allowlist-cidrs.d"

  for f in "$domains_d/custom.txt" "$proxy_d/custom.txt" "$cidrs_d/custom.txt"; do
    if [[ ! -f "$f" && -f "${f}.example" ]]; then
      cp "${f}.example" "$f"
      printf 'Created %s from template (gitignored — add your own entries there)\n' "$f"
    fi
  done

  printf 'Generating allowlists from sandbox.conf...\n'

  {
    printf '# AUTO-GENERATED by build.sh — do not edit directly.\n'
    printf '# Edit files in allowlist-domains.d/ and run: ./build.sh\n\n'
    include_fragment         "$domains_d/base.txt"
    include_if_enabled       "$domains_d/github-cli.txt"      github-cli
    include_if_enabled       "$domains_d/github-copilot.txt"  copilot
    include_if_enabled       "$domains_d/kiro.txt"            kiro
    include_if_enabled       "$domains_d/claude-code.txt"     claude-code
    include_if_enabled       "$domains_d/codex.txt"           codex
    include_if_enabled       "$domains_d/gemini.txt"          gemini
    include_if_enabled       "$domains_d/graphify.txt"        graphify
    include_if_enabled       "$domains_d/yarn.txt"            yarn
    include_if_enabled       "$domains_d/kubectl.txt"         kubectl
    include_if_enabled       "$domains_d/aws-cli.txt"         aws-cli
    include_if_enabled       "$domains_d/azure-cli.txt"       azure-cli
    local _frag
    while IFS= read -r _frag; do include_fragment "$domains_d/${_frag}.txt"; done < <(active_tool_fragments)
    include_if_has_versions  "$domains_d/sdkman.txt"          openjdk graalvm-ce graalvm-oracle kotlin scala maven gradle
    include_if_has_versions  "$domains_d/openjdk.txt"         openjdk graalvm-ce graalvm-oracle
    include_fragment         "$domains_d/nvm.txt"
    include_fragment         "$domains_d/pyenv.txt"
    include_if_has_versions  "$domains_d/rvm.txt"             ruby rails
    include_if_has_versions  "$domains_d/rust.txt"            rust
    include_if_has_versions  "$domains_d/go.txt"              go
    include_if_enabled       "$domains_d/goreleaser.txt"      goreleaser
    include_if_enabled       "$domains_d/vale.txt"            vale
    if is_active angular-cli; then include_fragment "$domains_d/angular-cli.txt"; fi
    include_fragment         "$domains_d/custom.txt"
  } > "${script_dir}/allowlist-domains.txt"

  {
    printf '# AUTO-GENERATED by build.sh — do not edit directly.\n'
    printf '# Edit files in allowlist-proxy-domains.d/ and run: ./build.sh\n\n'
    include_if_enabled  "$proxy_d/github-copilot.txt"  copilot
    include_if_enabled  "$proxy_d/kiro.txt"            kiro
    include_if_enabled  "$proxy_d/claude-code.txt"     claude-code
    include_if_enabled  "$proxy_d/codex.txt"           codex
    include_if_enabled  "$proxy_d/gemini.txt"          gemini
    include_if_enabled  "$proxy_d/graphify.txt"        graphify
    local _pfrag
    while IFS= read -r _pfrag; do include_fragment "$proxy_d/${_pfrag}.txt"; done < <(active_tool_fragments)
    include_fragment    "$proxy_d/custom.txt"
  } > "${script_dir}/allowlist-proxy-domains.txt"

  {
    printf '# AUTO-GENERATED by build.sh — do not edit directly.\n'
    printf '# Edit files in allowlist-cidrs.d/ and run: ./build.sh\n\n'
    include_fragment    "$cidrs_d/base.txt"
    include_if_enabled  "$cidrs_d/github-copilot.txt"  copilot
    include_fragment    "$cidrs_d/custom.txt"
  } > "${script_dir}/allowlist-cidrs.txt"
}

# ── Build-arg generation ─────────────────────────────────────────────────────────

build_args_from_config() {
  local -n _args=$1

  local component arg mapping
  local bool_mappings=(
    "copilot:INSTALL_COPILOT"
    "kiro:INSTALL_KIRO"
    "claude-code:INSTALL_CLAUDE_CODE"
    "codex:INSTALL_CODEX"
    "gemini:INSTALL_GEMINI"
    "graphify:INSTALL_GRAPHIFY"
    "kubectl:INSTALL_KUBECTL"
    "aws-cli:INSTALL_AWS_CLI"
    "azure-cli:INSTALL_AZURE_CLI"
    "github-cli:INSTALL_GITHUB_CLI"
    "yarn:INSTALL_YARN"
    "pnpm:INSTALL_PNPM"
    "goreleaser:INSTALL_GORELEASER"
    "vale:INSTALL_VALE"
    "qmd:INSTALL_QMD"
    "bun:INSTALL_BUN"
  )
  for mapping in "${bool_mappings[@]}"; do
    component="${mapping%%:*}"
    arg="${mapping##*:}"
    if is_enabled "$component"; then value=1; else value=0; fi
    _args+=(--build-arg "${arg}=${value}")
  done

  if is_enabled copilot && ! is_enabled github-cli; then
    _args+=(--build-arg "INSTALL_GITHUB_CLI=1")
  fi

  _args+=(--build-arg "TOOL_VERSIONS=$(tool_versions_arg)")

  local angular_raw; angular_raw=$(get_versions angular-cli)
  if [[ "$angular_raw" == "ON" ]]; then
    _args+=(--build-arg "ANGULAR_CLI_VERSION=latest")
  elif [[ -n "$angular_raw" && "$angular_raw" != "OFF" ]]; then
    _args+=(--build-arg "ANGULAR_CLI_VERSION=${angular_raw}")
  else
    _args+=(--build-arg "ANGULAR_CLI_VERSION=")
  fi

  local jvm_keys=(openjdk graalvm-ce graalvm-oracle kotlin scala maven gradle)
  if any_has_versions "${jvm_keys[@]}"; then
    _args+=(--build-arg "INSTALL_SDKMAN=1")
  else
    _args+=(--build-arg "INSTALL_SDKMAN=0")
  fi

  local ver
  ver="$(get_versions openjdk)";        _args+=(--build-arg "OPENJDK_VERSIONS=$(versions_to_space "$ver")")
  ver="$(get_versions graalvm-ce)";     _args+=(--build-arg "GRAALVM_VERSIONS=$(versions_to_space "$ver")")
  ver="$(get_versions graalvm-oracle)"; _args+=(--build-arg "GRAALVM_ORACLE_VERSIONS=$(versions_to_space "$ver")")
  ver="$(get_versions kotlin)";         _args+=(--build-arg "KOTLIN_VERSIONS=$(versions_to_space "$ver")")
  ver="$(get_versions scala)";          _args+=(--build-arg "SCALA_VERSIONS=$(versions_to_space "$ver")")
  ver="$(get_versions maven)";          _args+=(--build-arg "MAVEN_VERSIONS=$(versions_to_space "$ver")")
  ver="$(get_versions gradle)";         _args+=(--build-arg "GRADLE_VERSIONS=$(versions_to_space "$ver")")
  ver="$(get_versions node)";           _args+=(--build-arg "NODE_EXTRA_VERSIONS=$(versions_to_space "$ver")")

  ver="$(get_versions nvm-version)"
  if [[ -n "$ver" ]]; then
    _args+=(--build-arg "NVM_VERSION=$ver")
  fi

  ver="$(get_versions python)"; _args+=(--build-arg "PYTHON_EXTRA_VERSIONS=$(versions_to_space "$ver")")
  ver="$(get_versions ruby)";   _args+=(--build-arg "RUBY_VERSION=$ver")
  ver="$(get_versions rails)";  _args+=(--build-arg "RAILS_VERSION=$ver")
  ver="$(get_versions rust)";   _args+=(--build-arg "RUST_TOOLCHAIN=$ver")
  ver="$(get_versions go)";     _args+=(--build-arg "GO_VERSION=$ver")
}

# ── Tool descriptor helpers ──────────────────────────────────────────────────────

# tool_versions_arg — "name=version;..." for every active tool (build-arg value).
tool_versions_arg() {
  local name raw ver out=""
  while IFS= read -r name; do
    raw=$(get_versions "$name")
    if [[ "$raw" == "ON" ]]; then ver="latest"
    elif [[ -n "$raw" && "$raw" != "OFF" ]]; then ver="$raw"
    else continue; fi
    out+="${name}=${ver};"
  done < <(tools_list_names)
  printf '%s' "${out%;}"
}

# active_tool_fragments — unique allowlist_fragment names of active tools.
active_tool_fragments() {
  local name
  while IFS= read -r name; do
    is_active "$name" || continue
    tools_read_descriptor "$name" || continue
    [[ -n "$TOOL_allowlist_fragment" ]] && printf '%s\n' "$TOOL_allowlist_fragment"
  done < <(tools_list_names) | sort -u
}

# preflight_private_tools — warn (non-fatal) when an active private tool has no token.
preflight_private_tools() {
  local token="${GITHUB_TOKEN:-${GITHUB_PERSONAL_ACCESS_TOKEN:-}}"
  [[ -n "$token" ]] && return 0
  local name warned=0
  while IFS= read -r name; do
    is_active "$name" || continue
    tools_read_descriptor "$name" || continue
    [[ "$TOOL_private" == "yes" ]] || continue
    if [[ "$warned" == 0 ]]; then
      printf '\n════════════════════════════════════════════════════════════════\n' >&2
      printf 'WARNING: no GITHUB_TOKEN set, but a PRIVATE tool is enabled:\n' >&2
      warned=1
    fi
    printf '  - %s (%s) will be SKIPPED without a token.\n' "$name" "$TOOL_repo" >&2
  done < <(tools_list_names)
  if [[ "$warned" == 1 ]]; then
    printf '  Set GITHUB_TOKEN on the host and rebuild: ./build.sh\n' >&2
    printf '════════════════════════════════════════════════════════════════\n\n' >&2
  fi
}

# ── Build ──────────────────────────────────────────────────────────────────────

build_image() {
  check_config
  validate_config
  local build_image_name="${1:-$image_name}"
  local build_args=()

  generate_allowlists
  build_args_from_config build_args

  # Targeted agent-layer cache-bust. Default 0 reuses the cache; runme.sh sets a
  # fresh timestamp to force-refresh the (unpinned) agent CLIs when the image is
  # stale, without rebuilding the heavy toolchain layers. See the AGENTS_CACHE_BUST
  # ARG in the Dockerfile.
  build_args+=(--build-arg "AGENTS_CACHE_BUST=${AGENTS_CACHE_BUST:-0}")

  if [[ "${NO_CACHE:-0}" == "1" ]]; then
    build_args+=(--no-cache)
  fi

  local _gh_build_token="${GITHUB_TOKEN:-${GITHUB_PERSONAL_ACCESS_TOKEN:-}}"
  if [[ -n "$_gh_build_token" ]]; then
    export GITHUB_TOKEN="$_gh_build_token"
    build_args+=(--secret id=github_token,env=GITHUB_TOKEN)
  fi

  preflight_private_tools

  docker build "${build_args[@]}" -t "$build_image_name" "$script_dir"
}

# Allow tests to source this file for its pure helpers without building.
[[ "${BASH_SOURCE[0]}" != "${0}" ]] && return 0

# ── Entry point ──────────────────────────────────────────────────────────────────

positional=()
for arg in "$@"; do
  case "$arg" in
    --no-cache)   NO_CACHE=1 ;;
    -h|--help|help|usage) usage; exit 0 ;;
    *)            positional+=("$arg") ;;
  esac
done

build_image "${positional[0]:-$image_name}"
