#!/usr/bin/env bash
set -euo pipefail

# build.sh — build the AI sandbox image.
#
# Reads sandbox.conf, regenerates the allowlist-*.txt files from the *.d/
# fragment directories, and passes a --build-arg per component to docker build.

_here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=SCRIPTDIR/sandbox-common.sh
source "${_here}/sandbox-common.sh"

usage() {
  cat <<'EOF'
Usage:
  ./build.sh [image-name] [--no-cache]

Builds the AI sandbox image (reads sandbox.conf, regenerates allowlists).

Arguments:
  image-name   Optional image tag to build (default: $IMAGE_NAME or ai-sandbox).

Flags:
  --no-cache   Pass --no-cache to docker build (also: NO_CACHE=1 ./build.sh).

Environment variables:
  IMAGE_NAME   Image to build (default: ai-sandbox).
  NO_CACHE     Set to 1 to pass --no-cache to docker build.
  GITHUB_TOKEN Build-time only. Passed to docker build as a BuildKit secret
               (--secret id=github_token) so install-tools.sh can use the
               authenticated GitHub API (5000 req/h vs 60 req/h). Never written
               into any image layer or visible in `docker history`. If unset,
               GITHUB_PERSONAL_ACCESS_TOKEN is used as a fallback.

Configuration:
  Edit sandbox.conf to enable or disable optional components before building.
EOF
}

# ── Validation ─────────────────────────────────────────────────────────────────

validate_config() {
  if is_enabled copilot && ! is_enabled github-cli; then
    printf 'NOTE: copilot=ON implies github-cli. gh CLI will be installed for authentication.\n' >&2
  fi
  local angular_val; angular_val=$(get_versions angular-cli)
  if [[ "$angular_val" == *,* ]]; then
    printf 'ERROR: angular-cli only supports a single version (got: "%s").\n' "$angular_val" >&2
    printf '       Use ON (latest), a single version number (e.g. 19), or OFF.\n' >&2
    exit 1
  fi
  local jvm_key jvm_val ver
  for jvm_key in openjdk graalvm-ce graalvm-oracle kotlin scala maven gradle; do
    jvm_val=$(version_list "$jvm_key")
    [[ -z "$jvm_val" ]] && continue
    IFS=',' read -ra _vers <<< "$jvm_val"
    for ver in "${_vers[@]}"; do
      ver="${ver// /}"
      if [[ "$ver" != *.* ]]; then
        printf 'ERROR: %s version "%s" looks like a major version only.\n' "$jvm_key" "$ver" >&2
        printf '       SDKMAN requires full patch versions, e.g. 21.0.5 not 21.\n' >&2
        printf '       Run "sdk list java" inside a container to see valid identifiers.\n' >&2
        exit 1
      fi
    done
  done
  # db-clients is a CLOSED set, not free-form versions. Catch a typo here with a clear
  # error instead of letting it through to a warning buried in the docker build output
  # (where it would still have flipped KEEP_BUILD_TOOLCHAIN on and grown the image).
  local db_val db_c
  db_val=$(version_list db-clients)
  if [[ -n "$db_val" ]]; then
    IFS=',' read -ra _dbs <<< "$db_val"
    for db_c in "${_dbs[@]}"; do
      db_c="${db_c// /}"
      [[ -z "$db_c" ]] && continue
      case "$db_c" in
        pg|mysql|mongo) ;;
        *)
          printf 'ERROR: unknown db-clients entry "%s".\n' "$db_c" >&2
          printf '       Allowed (comma-separated subset): pg, mysql, mongo. Leave empty to skip.\n' >&2
          exit 1
          ;;
      esac
    done
  fi
}

# ── Allowlist generation ─────────────────────────────────────────────────────────

include_fragment() {
  local fragment="$1"
  if [[ -f "$fragment" ]]; then cat "$fragment"; fi
}

include_if_enabled() {
  local fragment="$1"; shift
  if any_enabled "$@"; then
    include_fragment "$fragment"
  fi
}

include_if_has_versions() {
  local fragment="$1"; shift
  if any_has_versions "$@"; then
    include_fragment "$fragment"
  fi
}

generate_allowlists() {
  local domains_d="${script_dir}/allowlist-domains.d"
  local proxy_d="${script_dir}/allowlist-proxy-domains.d"
  local cidrs_d="${script_dir}/allowlist-cidrs.d"

  for f in "$domains_d/custom.txt" "$proxy_d/custom.txt" "$cidrs_d/custom.txt"; do
    if [[ ! -f "$f" && -f "${f}.example" ]]; then
      cp "${f}.example" "$f"
      printf 'Created %s from template (gitignored — add your own entries there)\n' "$f"
    fi
  done

  printf 'Generating allowlists from sandbox.conf...\n'

  {
    printf '# AUTO-GENERATED by build.sh — do not edit directly.\n'
    printf '# Edit files in allowlist-domains.d/ and run: ./build.sh\n\n'
    include_fragment         "$domains_d/base.txt"
    include_if_enabled       "$domains_d/github-cli.txt"      github-cli
    include_if_enabled       "$domains_d/github-copilot.txt"  copilot
    include_if_enabled       "$domains_d/kiro.txt"            kiro
    include_if_enabled       "$domains_d/claude-code.txt"     claude-code
    include_if_enabled       "$domains_d/codex.txt"           codex
    include_if_enabled       "$domains_d/gemini.txt"          gemini
    include_if_enabled       "$domains_d/graphify.txt"        graphify
    include_if_enabled       "$domains_d/yarn.txt"            yarn
    include_if_enabled       "$domains_d/kubectl.txt"         kubectl
    include_if_enabled       "$domains_d/aws-cli.txt"         aws-cli
    include_if_enabled       "$domains_d/azure-cli.txt"       azure-cli
    local _frag
    while IFS= read -r _frag; do include_fragment "$domains_d/${_frag}.txt"; done < <(active_tool_fragments)
    include_if_has_versions  "$domains_d/sdkman.txt"          openjdk graalvm-ce graalvm-oracle kotlin scala maven gradle
    include_if_has_versions  "$domains_d/openjdk.txt"         openjdk graalvm-ce graalvm-oracle
    include_fragment         "$domains_d/nvm.txt"
    include_fragment         "$domains_d/pyenv.txt"
    include_if_has_versions  "$domains_d/rvm.txt"             ruby
    if db_clients_has mongo; then include_fragment "$domains_d/mongodb.txt"; fi
    include_if_has_versions  "$domains_d/rust.txt"            rust
    include_if_has_versions  "$domains_d/go.txt"              go
    include_if_enabled       "$domains_d/goreleaser.txt"      goreleaser
    include_if_enabled       "$domains_d/vale.txt"            vale
    if is_active angular-cli; then include_fragment "$domains_d/angular-cli.txt"; fi
    include_fragment         "$domains_d/custom.txt"
  } > "${script_dir}/allowlist-domains.txt"

  {
    printf '# AUTO-GENERATED by build.sh — do not edit directly.\n'
    printf '# Edit files in allowlist-proxy-domains.d/ and run: ./build.sh\n\n'
    include_if_enabled  "$proxy_d/github-copilot.txt"  copilot
    include_if_enabled  "$proxy_d/kiro.txt"            kiro
    include_if_enabled  "$proxy_d/claude-code.txt"     claude-code
    include_if_enabled  "$proxy_d/codex.txt"           codex
    include_if_enabled  "$proxy_d/gemini.txt"          gemini
    include_if_enabled  "$proxy_d/graphify.txt"        graphify
    local _pfrag
    while IFS= read -r _pfrag; do include_fragment "$proxy_d/${_pfrag}.txt"; done < <(active_tool_fragments)
    include_fragment    "$proxy_d/custom.txt"
  } > "${script_dir}/allowlist-proxy-domains.txt"

  {
    printf '# AUTO-GENERATED by build.sh — do not edit directly.\n'
    printf '# Edit files in allowlist-cidrs.d/ and run: ./build.sh\n\n'
    include_fragment    "$cidrs_d/base.txt"
    include_if_enabled  "$cidrs_d/github-copilot.txt"  copilot
    include_fragment    "$cidrs_d/custom.txt"
  } > "${script_dir}/allowlist-cidrs.txt"
}

# ── Build-arg generation ─────────────────────────────────────────────────────────

build_args_from_config() {
  local -n _args=$1

  local component arg mapping
  local bool_mappings=(
    "kiro:INSTALL_KIRO"
    "kubectl:INSTALL_KUBECTL"
    "aws-cli:INSTALL_AWS_CLI"
    "azure-cli:INSTALL_AZURE_CLI"
    "github-cli:INSTALL_GITHUB_CLI"
    "yarn:INSTALL_YARN"
    "pnpm:INSTALL_PNPM"
    "goreleaser:INSTALL_GORELEASER"
    "qmd:INSTALL_QMD"
    "bun:INSTALL_BUN"
    "imagemagick:INSTALL_IMAGEMAGICK"
    "wkhtmltopdf:INSTALL_WKHTMLTOPDF"
  )
  for mapping in "${bool_mappings[@]}"; do
    component="${mapping%%:*}"
    arg="${mapping##*:}"
    if is_enabled "$component"; then value=1; else value=0; fi
    _args+=(--build-arg "${arg}=${value}")
  done

  if is_enabled copilot && ! is_enabled github-cli; then
    _args+=(--build-arg "INSTALL_GITHUB_CLI=1")
  fi

  _args+=(--build-arg "TOOL_VERSIONS=$(tool_versions_arg)")

  local angular_raw; angular_raw=$(get_versions angular-cli)
  if [[ "$angular_raw" == "ON" ]]; then
    _args+=(--build-arg "ANGULAR_CLI_VERSION=latest")
  elif [[ -n "$angular_raw" && "$angular_raw" != "OFF" ]]; then
    _args+=(--build-arg "ANGULAR_CLI_VERSION=${angular_raw}")
  else
    _args+=(--build-arg "ANGULAR_CLI_VERSION=")
  fi

  local jvm_keys=(openjdk graalvm-ce graalvm-oracle kotlin scala maven gradle)
  if any_has_versions "${jvm_keys[@]}"; then
    _args+=(--build-arg "INSTALL_SDKMAN=1")
  else
    _args+=(--build-arg "INSTALL_SDKMAN=0")
  fi

  local ver
  ver="$(version_list openjdk)";        _args+=(--build-arg "OPENJDK_VERSIONS=$(versions_to_space "$ver")")
  ver="$(version_list graalvm-ce)";     _args+=(--build-arg "GRAALVM_VERSIONS=$(versions_to_space "$ver")")
  ver="$(version_list graalvm-oracle)"; _args+=(--build-arg "GRAALVM_ORACLE_VERSIONS=$(versions_to_space "$ver")")
  ver="$(version_list kotlin)";         _args+=(--build-arg "KOTLIN_VERSIONS=$(versions_to_space "$ver")")
  ver="$(version_list scala)";          _args+=(--build-arg "SCALA_VERSIONS=$(versions_to_space "$ver")")
  ver="$(version_list maven)";          _args+=(--build-arg "MAVEN_VERSIONS=$(versions_to_space "$ver")")
  ver="$(version_list gradle)";         _args+=(--build-arg "GRADLE_VERSIONS=$(versions_to_space "$ver")")
  ver="$(version_list node)";           _args+=(--build-arg "NODE_EXTRA_VERSIONS=$(versions_to_space "$ver")")

  ver="$(get_versions nvm-version)"
  if [[ -n "$ver" ]]; then
    _args+=(--build-arg "NVM_VERSION=$ver")
  fi

  ver="$(version_list python)"; _args+=(--build-arg "PYTHON_EXTRA_VERSIONS=$(versions_to_space "$ver")")
  ver="$(version_list rust)";   _args+=(--build-arg "RUST_TOOLCHAIN=$ver")
  ver="$(version_list go)";     _args+=(--build-arg "GO_VERSION=$ver")

  # DB client libraries (client/dev libs + CLIs only — never servers).
  ver="$(version_list db-clients)"; _args+=(--build-arg "DB_CLIENTS=$(versions_to_space "$ver")")

  # Retain a runtime build toolchain so native extensions compile at runtime.
  # Needed whenever Ruby is present or a DB driver will be built — and now also
  # on request, because until `c-toolchain` existed there was no way to ASK for
  # a C compiler: it arrived only as a side effect of enabling Ruby or a DB
  # client, so a Go developer wanting `go test -race` (cgo, hence gcc) had to
  # switch on an unrelated language runtime to get one. Reported from a real
  # session on the dtmgd Go CLI, where the fallback was relocating 31 arm64
  # .debs by hand and wrapping gcc with -B and LD_LIBRARY_PATH to make a
  # displaced cc1 find its own support objects.
  #
  # DELIBERATELY NOT IMPLIED BY `go`. Go only needs a C compiler for cgo, which
  # most builds never touch; wiring it to the language key would grow every Go
  # image for a capability most of them never use. It is opt-in for the same
  # reason db-clients is.
  if has_versions ruby || has_versions db-clients || is_enabled c-toolchain; then
    _args+=(--build-arg "KEEP_BUILD_TOOLCHAIN=1")
  else
    _args+=(--build-arg "KEEP_BUILD_TOOLCHAIN=0")
  fi

  # Ruby-build/rvm dependency layer is baked only when Ruby is requested;
  # rvm itself and the interpreter are installed per-user at runtime.
  if has_versions ruby; then _args+=(--build-arg "RUBY_RUNTIME=1"); else _args+=(--build-arg "RUBY_RUNTIME=0"); fi
}

# ── Tool descriptor helpers ──────────────────────────────────────────────────────

# tool_versions_arg — "name=version;..." for every active tool (build-arg value).
tool_versions_arg() {
  # Named "pairs", not "out": sandbox-common.sh's enabled_agents_csv/-like
  # helpers use a local array ALSO named `out` — shellcheck's array/scalar
  # type tracking isn't scope-aware, so a plain string `out` here reads as
  # the same variable and falsely triggers SC2178/SC2179. Renaming sidesteps
  # the collision instead of suppressing a real pattern.
  local name raw ver pairs=""
  while IFS= read -r name; do
    raw=$(get_versions "$name")
    if [[ "$raw" == "ON" ]]; then ver="latest"
    elif [[ -n "$raw" && "$raw" != "OFF" ]]; then ver="$raw"
    else continue; fi
    pairs+="${name}=${ver};"
  done < <(tools_list_names)
  printf '%s' "${pairs%;}"
}

# active_tool_fragments — unique allowlist_fragment names of active tools.
active_tool_fragments() {
  local name
  while IFS= read -r name; do
    is_active "$name" || continue
    tools_read_descriptor "$name" || continue
    [[ -n "$TOOL_allowlist_fragment" ]] && printf '%s\n' "$TOOL_allowlist_fragment"
  done < <(tools_list_names) | sort -u
}

# preflight_private_tools — warn (non-fatal) when an active private tool has no token.
preflight_private_tools() {
  local token="${GITHUB_TOKEN:-${GITHUB_PERSONAL_ACCESS_TOKEN:-}}"
  [[ -n "$token" ]] && return 0
  local name warned=0
  while IFS= read -r name; do
    is_active "$name" || continue
    tools_read_descriptor "$name" || continue
    # shellcheck disable=SC2154  # TOOL_private: set by tools_read_descriptor() in tools-lib.sh (sourced)
    [[ "$TOOL_private" == "yes" ]] || continue
    if [[ "$warned" == 0 ]]; then
      printf '\n════════════════════════════════════════════════════════════════\n' >&2
      printf 'WARNING: no GITHUB_TOKEN set, but a PRIVATE tool is enabled:\n' >&2
      warned=1
    fi
    # shellcheck disable=SC2154  # TOOL_repo: set by tools_read_descriptor() in tools-lib.sh (sourced)
    printf '  - %s (%s) will be SKIPPED without a token.\n' "$name" "$TOOL_repo" >&2
  done < <(tools_list_names)
  if [[ "$warned" == 1 ]]; then
    printf '  Set GITHUB_TOKEN on the host and rebuild: ./build.sh\n' >&2
    printf '════════════════════════════════════════════════════════════════\n\n' >&2
  fi
}

# ── Build ──────────────────────────────────────────────────────────────────────

build_image() {
  check_config
  validate_config
  local build_image_name="${1:-$image_name}"
  local build_args=()

  generate_allowlists
  build_args_from_config build_args

  if [[ "${NO_CACHE:-0}" == "1" ]]; then
    build_args+=(--no-cache)
  fi

  local _gh_build_token="${GITHUB_TOKEN:-${GITHUB_PERSONAL_ACCESS_TOKEN:-}}"
  if [[ -n "$_gh_build_token" ]]; then
    export GITHUB_TOKEN="$_gh_build_token"
    # shellcheck disable=SC2054  # one --secret flag value; the comma is docker's id=...,env=... syntax, not an array separator
    build_args+=(--secret id=github_token,env=GITHUB_TOKEN)
  fi

  preflight_private_tools

  # Image this tag pointed at before the build, so the replaced layer set can be
  # dropped afterwards instead of accumulating as a dangling image.
  local old_image_id
  old_image_id="$(docker image inspect --format '{{.Id}}' "$build_image_name" 2>/dev/null || true)"

  docker build "${build_args[@]}" -t "$build_image_name" "$script_dir"

  # Only after a successful build: clean up the image it replaced.
  local new_image_id
  new_image_id="$(docker image inspect --format '{{.Id}}' "$build_image_name" 2>/dev/null || true)"
  remove_replaced_image "$old_image_id" "$new_image_id"
}

# Allow tests to source this file for its pure helpers without building.
[[ "${BASH_SOURCE[0]}" != "${0}" ]] && return 0

# ── Entry point ──────────────────────────────────────────────────────────────────

positional=()
for arg in "$@"; do
  case "$arg" in
    --no-cache)   NO_CACHE=1 ;;
    -h|--help|help|usage) usage; exit 0 ;;
    *)            positional+=("$arg") ;;
  esac
done

build_image "${positional[0]:-$image_name}"
