#!/usr/bin/env bash
# install-tools.sh — install external CLIs described in tools.d/ into the image.
# Driven by TOOL_VERSIONS (semicolon-separated name=version pairs, version
# "latest" or "x.y.z"), generated by build.sh from sandbox.conf + tools.d/.
# Replaces the former install-dt-tools.sh.
#
# Env:
#   TOOL_VERSIONS  "name=version;..."
#   GITHUB_TOKEN   optional for public tools (raises API rate limit 60→5000/h);
#                  REQUIRED for private tools (private=yes) — even when pinned.
# Non-fatal: any per-tool failure warns and is skipped; the build still succeeds.
set -uo pipefail

TOOLS_D_DIR="${TOOLS_D_DIR:-/etc/ai-containers/tools.d}"
# shellcheck source=/dev/null
source "${TOOLS_LIB:-/etc/ai-containers/tools-lib.sh}"

ARCH="${ARCH:-$(uname -m | sed 's/x86_64/amd64/; s/aarch64/arm64/')}"
OS="${OS:-$(uname -s | tr '[:upper:]' '[:lower:]')}"

if [ -n "${GITHUB_TOKEN:-}" ]; then
  AUTH_ARGS=(-H "Authorization: Bearer ${GITHUB_TOKEN}")
else
  AUTH_ARGS=()
fi

# api_get <url> — GET the GitHub API with retries; echo body (empty on failure).
api_get() {
  local url="$1" body="" i
  for i in 1 2 3; do
    body=$(curl -fsSL ${AUTH_ARGS[@]+"${AUTH_ARGS[@]}"} \
             -H "Accept: application/vnd.github+json" "$url") && [ -n "$body" ] && break
    echo "  API attempt $i failed, retrying in 5s..." >&2; sleep 5
  done
  printf '%s' "$body"
}

# asset_name <binary> <tag> — release asset filename for this OS/ARCH.
asset_name() { printf '%s_%s_%s_%s.tar.gz' "$1" "${2#v}" "$OS" "$ARCH"; }

# parse_versions <str> — echo "name<TAB>version" per entry (pure; for tests/main).
parse_versions() {
  local IFS=';' entry name version
  read -ra _e <<< "$1"
  for entry in "${_e[@]}"; do
    [ -n "$entry" ] || continue
    name="${entry%%=*}"; version="${entry#*=}"
    printf '%s\t%s\n' "$name" "$version"
  done
}

install_one() {
  local name="$1" version="$2"
  tools_read_descriptor "$name" || { echo "WARNING: no descriptor for '$name' — skipping."; return 0; }
  [ -n "$version" ] || return 0
  local private="$TOOL_private" repo="$TOOL_repo" binary="$TOOL_binary"

  if [ "$private" = "yes" ] && [ -z "${GITHUB_TOKEN:-}" ]; then
    echo "════════════════════════════════════════════════════════════════"
    echo "WARNING: '$name' is a PRIVATE repo (${repo}) and requires GITHUB_TOKEN."
    echo "         No token provided — skipping ${name}."
    echo "         Set GITHUB_TOKEN on the host and rebuild: ./build.sh"
    echo "════════════════════════════════════════════════════════════════"
    return 0
  fi

  local tag an
  if [ "$private" = "yes" ]; then
    local api="https://api.github.com/repos/${repo}/releases" release_json
    if [ "$version" = "latest" ]; then release_json=$(api_get "${api}/latest")
    else release_json=$(api_get "${api}/tags/v${version#v}"); fi
    tag=$(printf '%s' "$release_json" | jq -r '.tag_name // empty')
    [ -n "$tag" ] || { echo "WARNING: could not resolve ${name} release — skipping."; return 0; }
    an=$(asset_name "$binary" "$tag")
    local asset_id
    asset_id=$(printf '%s' "$release_json" | jq -r --arg n "$an" '.assets[] | select(.name==$n) | .id')
    [ -n "$asset_id" ] || { echo "WARNING: asset ${an} not found for ${name} ${tag} — skipping."; return 0; }
    echo "Installing ${name} ${tag} (private)..."
    if ! curl -fsSL ${AUTH_ARGS[@]+"${AUTH_ARGS[@]}"} -H "Accept: application/octet-stream" \
           "https://api.github.com/repos/${repo}/releases/assets/${asset_id}" \
         | tar xz -C /usr/local/bin "$binary"; then
      echo "WARNING: download/extract failed for ${name} ${tag} — skipping."; return 0
    fi
  else
    if [ "$version" = "latest" ]; then
      tag=$(printf '%s' "$(api_get "https://api.github.com/repos/${repo}/releases/latest")" \
              | jq -r '.tag_name // empty')
      if [ -z "$tag" ]; then
        echo "WARNING: could not resolve latest ${name} (rate limit?) — skipping."
        echo "         Pin a version in sandbox.conf (e.g. ${name}=0.25.0) or set GITHUB_TOKEN."
        return 0
      fi
    else
      tag="v${version#v}"
    fi
    an=$(asset_name "$binary" "$tag")
    echo "Installing ${name} ${tag}..."
    if ! curl -fsSL "https://github.com/${repo}/releases/download/${tag}/${an}" \
         | tar xz -C /usr/local/bin "$binary"; then
      echo "WARNING: download/extract failed for ${name} ${tag} — skipping."
      echo "         Check that version '${tag#v}' exists at https://github.com/${repo}/releases"
      return 0
    fi
  fi
  chmod +x "/usr/local/bin/${binary}"
  echo "Installed ${name} ${tag}"
}

main() {
  local line name version
  while IFS=$'\t' read -r name version; do
    install_one "$name" "$version"
  done < <(parse_versions "${TOOL_VERSIONS:-}")
}

# Execute only when run directly; allow sourcing for unit tests.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then main; fi
