#!/usr/bin/env bash
# install-tools.sh — install external CLIs described in tools.d/ into the image.
# Driven by TOOL_VERSIONS (semicolon-separated name=version pairs, version
# "latest" or "x.y.z"), generated by build.sh from sandbox.conf + tools.d/.
# Replaces the former install-dt-tools.sh.
#
# Env:
#   TOOL_VERSIONS  "name=version;..."
#   GITHUB_TOKEN   optional for public tools (raises API rate limit 60→5000/h);
#                  REQUIRED for private tools (private=yes) — even when pinned.
# Non-fatal: any per-tool failure warns and is skipped; the build still succeeds.
set -uo pipefail

TOOLS_D_DIR="${TOOLS_D_DIR:-/etc/ai-containers/tools.d}"
# shellcheck source=/dev/null
source "${TOOLS_LIB:-/etc/ai-containers/tools-lib.sh}"

ARCH="${ARCH:-$(uname -m | sed 's/x86_64/amd64/; s/aarch64/arm64/')}"
OS="${OS:-$(uname -s | tr '[:upper:]' '[:lower:]')}"
# Where binaries land. Always /usr/local/bin in the image; overridable so the
# unit tests can exercise the installers without writing outside their tmpdir.
BIN_DIR="${TOOLS_BIN_DIR:-/usr/local/bin}"

if [ -n "${GITHUB_TOKEN:-}" ]; then
  AUTH_ARGS=(-H "Authorization: Bearer ${GITHUB_TOKEN}")
else
  AUTH_ARGS=()
fi

# api_get <url> — GET the GitHub API with retries; echo body (empty on failure).
api_get() {
  local url="$1" body="" i
  for i in 1 2 3; do
    body=$(curl -fsSL ${AUTH_ARGS[@]+"${AUTH_ARGS[@]}"} \
             -H "Accept: application/vnd.github+json" "$url") && [ -n "$body" ] && break
    # A FAILED TRANSFER IS NOT A RESPONSE. Reaching here means curl exited
    # non-zero or handed back nothing, and `body` still holds whatever it wrote
    # to stdout first. `-f` suppresses an HTTP error page, but a connection
    # reset part-way through a successful response does not: curl exits
    # non-zero having already written a PARTIAL body. Without this line the
    # last attempt's fragment is returned as if it were the API's answer, and
    # install_one parses it for a tag.
    body=""
    [ "$i" -lt 3 ] && { echo "  API attempt $i failed, retrying in 5s..." >&2; sleep 5; }
  done
  printf '%s' "$body"
}

# asset_name <binary> <tag> — release asset filename for this OS/ARCH.
asset_name() { printf '%s_%s_%s_%s.tar.gz' "$1" "${2#v}" "$OS" "$ARCH"; }

# install_repo_file <name> <ref> — install a prebuilt binary COMMITTED IN the
# repo (install=repo-file), rather than published as a release asset.
#
# Used by tools whose artifacts are vendored into a git repo, so there is no
# release to resolve and nothing to untar: the file at repo_path IS the binary.
# repo_path may contain ${ARCH}, expanded to this image's amd64/arm64.
#
# <ref> is a branch/tag/commit, or "latest" for the repo's default branch. The
# contents API with the raw media type streams the file itself; for a private
# repo GITHUB_TOKEN is required (the private=yes guard in install_one covers it).
install_repo_file() {
  local name="$1" ref="$2"
  # shellcheck disable=SC2154
  local repo="$TOOL_repo" binary="$TOOL_binary" path="$TOOL_repo_path"

  if [ -z "$repo" ] || [ -z "$path" ]; then
    echo "WARNING: ${name} sets install=repo-file but repo= or repo_path= is empty — skipping." >&2
    return 0
  fi

  path="$(expand_placeholders "$path" "$ref")"

  local url="https://api.github.com/repos/${repo}/contents/${path}"
  # "latest" means the default branch: send no ref and let GitHub decide.
  if [ "$ref" != "latest" ]; then
    url="${url}?ref=${ref}"
  elif [ -n "$TOOL_ref" ]; then
    url="${url}?ref=${TOOL_ref}"
  fi

  local dest="${BIN_DIR}/${binary}" tmp
  # mktemp, not a predictable name: /tmp is shared, and a pre-existing symlink at
  # a guessable path would otherwise be written through.
  if ! tmp="$(mktemp "${TMPDIR:-/tmp}/${binary}.XXXXXX")"; then
    echo "WARNING: could not create a temp file for ${name} — skipping." >&2
    return 0
  fi

  echo "Installing ${name} from ${repo}:${path}..."
  if ! curl -fsSL ${AUTH_ARGS[@]+"${AUTH_ARGS[@]}"} \
         -H "Accept: application/vnd.github.raw" "$url" -o "$tmp"; then
    echo "WARNING: download failed for ${name} (${repo}:${path}) — skipping." >&2
    echo "         Check the path exists on that ref and that GITHUB_TOKEN grants access." >&2
    rm -f "$tmp"
    return 0
  fi
  if [ ! -s "$tmp" ]; then
    echo "WARNING: ${name} downloaded empty — skipping." >&2
    rm -f "$tmp"
    return 0
  fi
  # The contents API answers a DIRECTORY path with 200 and a JSON listing, which
  # curl -f cannot distinguish from a file. Installing that as the binary would
  # "succeed" and only fail when the agent runs it.
  case "$(head -c 1 "$tmp")" in
    '['|'{')
      echo "WARNING: ${name}: the API returned JSON, not a file — is repo_path a directory?" >&2
      echo "         repo_path=${path}" >&2
      rm -f "$tmp"
      return 0
      ;;
  esac
  # Failures here are why this is checked: an unwritable BIN_DIR would otherwise
  # print "Installed" while nothing was installed.
  if ! mv "$tmp" "$dest" || ! chmod +x "$dest"; then
    echo "WARNING: could not install ${name} to ${dest} — skipping." >&2
    rm -f "$tmp"
    return 0
  fi
  echo "Installed ${name} (${repo}:${path})"
}

# expand_placeholders <template> <version> — substitute ${OS}, ${ARCH} and
# ${VERSION} in a descriptor-supplied template.
#
# BRACED FORMS ONLY, deliberately: an unbraced $OS/$ARCH is a plain substring
# match, so it would also fire inside $OSNAME or $ARCHY and corrupt the result.
# Any other ${...} is left alone.
expand_placeholders() {
  local t="$1" version="$2"
  t="${t//\$\{ARCH\}/$ARCH}"
  t="${t//\$\{OS\}/$OS}"
  t="${t//\$\{VERSION\}/$version}"
  printf '%s' "$t"
}

# install_url <name> <version> — install from a vendor-hosted URL (install=url).
#
# For tools distributed outside GitHub (Atlassian's acli, for example), so there
# is no release API to query and no token involved. A .tar.gz/.tgz is unpacked
# and <binary> is located ANYWHERE inside it — vendors commonly nest it in a
# version-named directory (acli ships acli_1.3.22-stable_linux_arm64/acli) — and
# any other URL is treated as the binary itself.
install_url() {
  local name="$1" version="$2"
  # shellcheck disable=SC2154  # TOOL_binary: set by tools_read_descriptor() in tools-lib.sh (sourced)
  local binary="$TOOL_binary" url
  # shellcheck disable=SC2154  # TOOL_url: set by tools_read_descriptor() in tools-lib.sh (sourced)
  url="$(expand_placeholders "$TOOL_url" "$version")"

  if [ -z "$url" ]; then
    echo "WARNING: ${name} sets install=url but url= is empty — skipping." >&2
    return 0
  fi

  # A url= with no ${VERSION} placeholder cannot honour a pinned version (some
  # vendors publish only a "latest" URL). Say so rather than silently installing
  # something other than what sandbox.conf asked for.
  if [ "$version" != "latest" ] && [ "${TOOL_url#*\$\{VERSION\}}" = "$TOOL_url" ]; then
    echo "NOTE: ${name}=${version} cannot be pinned: its url= has no \${VERSION} placeholder." >&2
    echo "      Installing whatever that URL currently serves; check with '${binary} --version'." >&2
  fi

  local work
  if ! work="$(mktemp -d "${TMPDIR:-/tmp}/${binary}.XXXXXX")"; then
    echo "WARNING: could not create a temp dir for ${name} — skipping." >&2
    return 0
  fi

  echo "Installing ${name} from ${url}..."
  local payload="$work/download"
  if ! curl -fsSL --retry 2 "$url" -o "$payload"; then
    echo "WARNING: download failed for ${name} (${url}) — skipping." >&2
    rm -rf "$work"; return 0
  fi
  if [ ! -s "$payload" ]; then
    echo "WARNING: ${name} downloaded empty — skipping." >&2
    rm -rf "$work"; return 0
  fi

  local found="$payload"
  # Match on the PATH only: a signed/CDN URL can carry ?query or #fragment after
  # the extension, and treating such an archive as a bare binary would install
  # the tarball itself and still report success.
  case "${url%%[?#]*}" in
    *.tar.gz|*.tgz)
      if ! tar xzf "$payload" -C "$work"; then
        echo "WARNING: could not unpack ${name} (${url}) — skipping." >&2
        rm -rf "$work"; return 0
      fi
      # Sorted, not `-print -quit`: find's traversal order is unspecified, so with
      # two same-named files the installed one would vary by machine.
      local candidates count
      candidates="$(find "$work" -type f -name "$binary" 2>/dev/null | sort)"
      count="$(printf '%s' "$candidates" | grep -c . || true)"
      if [ "$count" -eq 0 ]; then
        echo "WARNING: ${name}: no '${binary}' file inside the archive — skipping." >&2
        echo "         Set binary= to the executable's name as packaged." >&2
        rm -rf "$work"; return 0
      fi
      if [ "$count" -gt 1 ]; then
        echo "WARNING: ${name}: the archive holds ${count} files named '${binary}' — refusing to guess." >&2
        printf '%s\n' "$candidates" | sed "s|^${work}/|           |" >&2
        rm -rf "$work"; return 0
      fi
      found="$candidates"
      ;;
  esac

  if ! mv "$found" "${BIN_DIR}/${binary}" || ! chmod +x "${BIN_DIR}/${binary}"; then
    echo "WARNING: could not install ${name} to ${BIN_DIR}/${binary} — skipping." >&2
    rm -rf "$work"; return 0
  fi
  rm -rf "$work"
  echo "Installed ${name} (${url})"
}

# parse_versions <str> — echo "name<TAB>version" per entry (pure; for tests/main).
parse_versions() {
  local IFS=';' entry name version _e
  read -ra _e <<< "$1"
  for entry in "${_e[@]}"; do
    [ -n "$entry" ] || continue
    name="${entry%%=*}"; version="${entry#*=}"
    printf '%s\t%s\n' "$name" "$version"
  done
}

install_one() {
  local name="$1" version="$2"
  tools_read_descriptor "$name" || { echo "WARNING: no descriptor for '$name' — skipping." >&2; return 0; }
  [ -n "$version" ] || return 0
  # TOOL_* are set by tools_read_descriptor in the sourced tools-lib.sh.
  # shellcheck disable=SC2154
  local private="$TOOL_private" repo="$TOOL_repo" binary="$TOOL_binary"

  if [ "$private" = "yes" ] && [ -z "${GITHUB_TOKEN:-}" ]; then
    {
      echo "════════════════════════════════════════════════════════════════"
      echo "WARNING: '$name' is a PRIVATE repo (${repo}) and requires GITHUB_TOKEN."
      echo "         No token provided — skipping ${name}."
      echo "         Set GITHUB_TOKEN on the host and rebuild: ./build.sh"
      echo "════════════════════════════════════════════════════════════════"
    } >&2
    return 0
  fi

  # A vendored binary (install=repo-file) is fetched straight from the repo tree;
  # there is no release to resolve and no archive to unpack.
  # shellcheck disable=SC2154  # TOOL_install: set by tools_read_descriptor() in tools-lib.sh (sourced)
  if [ "$TOOL_install" = "repo-file" ]; then
    install_repo_file "$name" "$version"
    return 0
  fi

  # A vendor-hosted download (install=url) involves no GitHub repo at all.
  if [ "$TOOL_install" = "url" ]; then
    install_url "$name" "$version"
    return 0
  fi

  # Only the RELEASE path needs a repo — install=repo-file has its own check
  # above, and install=url involves no GitHub repo at all, so this sits
  # after both dispatches rather than beside the other descriptor reads.
  #
  # Without it an empty repo= flows straight into the API URL as
  # `https://api.github.com/repos//releases/latest`, and api_get retries that
  # three times with two 5-second sleeps before giving up: a malformed
  # descriptor costs ten seconds and then reports a doubled slash instead of the
  # field that is missing. install_repo_file has refused this exact condition
  # since it was written; the release path never did.
  if [ -z "$repo" ]; then
    echo "WARNING: ${name} has no repo= in its descriptor — skipping." >&2
    return 0
  fi

  local tag an
  if [ "$private" = "yes" ]; then
    local api="https://api.github.com/repos/${repo}/releases" release_json
    if [ "$version" = "latest" ]; then release_json=$(api_get "${api}/latest")
    else release_json=$(api_get "${api}/tags/v${version#v}"); fi
    tag=$(printf '%s' "$release_json" | jq -r '.tag_name // empty')
    [ -n "$tag" ] || { echo "WARNING: could not resolve ${name} release — skipping." >&2; return 0; }
    an=$(asset_name "$binary" "$tag")
    local asset_id
    asset_id=$(printf '%s' "$release_json" | jq -r --arg n "$an" '.assets[] | select(.name==$n) | .id')
    [ -n "$asset_id" ] || { echo "WARNING: asset ${an} not found for ${name} ${tag} — skipping." >&2; return 0; }
    echo "Installing ${name} ${tag} (private)..."
    if ! curl -fsSL ${AUTH_ARGS[@]+"${AUTH_ARGS[@]}"} -H "Accept: application/octet-stream" \
           "https://api.github.com/repos/${repo}/releases/assets/${asset_id}" \
         | tar xz -C "$BIN_DIR" "$binary"; then
      echo "WARNING: download/extract failed for ${name} ${tag} — skipping." >&2; return 0
    fi
  else
    if [ "$version" = "latest" ]; then
      tag=$(printf '%s' "$(api_get "https://api.github.com/repos/${repo}/releases/latest")" \
              | jq -r '.tag_name // empty')
      if [ -z "$tag" ]; then
        echo "WARNING: could not resolve latest ${name} (rate limit?) — skipping." >&2
        echo "         Pin a version in sandbox.conf (e.g. ${name}=0.25.0) or set GITHUB_TOKEN." >&2
        return 0
      fi
    else
      tag="v${version#v}"
    fi
    an=$(asset_name "$binary" "$tag")
    echo "Installing ${name} ${tag}..."
    if ! curl -fsSL "https://github.com/${repo}/releases/download/${tag}/${an}" \
         | tar xz -C "$BIN_DIR" "$binary"; then
      echo "WARNING: download/extract failed for ${name} ${tag} — skipping." >&2
      echo "         Check that version '${tag#v}' exists at https://github.com/${repo}/releases" >&2
      return 0
    fi
  fi
  chmod +x "${BIN_DIR}/${binary}"
  echo "Installed ${name} ${tag}"
}

main() {
  local name version
  while IFS=$'\t' read -r name version; do
    install_one "$name" "$version"
  done < <(parse_versions "${TOOL_VERSIONS:-}")
}

# Execute only when run directly; allow sourcing for unit tests.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then main; fi
