#!/usr/bin/env bash
# install-tools.sh — install external CLIs described in tools.d/ into the image.
# Driven by TOOL_VERSIONS (semicolon-separated name=version pairs, version
# "latest" or "x.y.z"), generated by build.sh from sandbox.conf + tools.d/.
# Replaces the former install-dt-tools.sh.
#
# Env:
#   TOOL_VERSIONS  "name=version;..."
#   GITHUB_TOKEN   optional for public tools (raises API rate limit 60→5000/h);
#                  REQUIRED for private tools (private=yes) — even when pinned.
# Non-fatal: any per-tool failure warns and is skipped; the build still succeeds.
set -uo pipefail

TOOLS_D_DIR="${TOOLS_D_DIR:-/etc/ai-containers/tools.d}"
# shellcheck source=/dev/null
source "${TOOLS_LIB:-/etc/ai-containers/tools-lib.sh}"

ARCH="${ARCH:-$(uname -m | sed 's/x86_64/amd64/; s/aarch64/arm64/')}"
OS="${OS:-$(uname -s | tr '[:upper:]' '[:lower:]')}"
# Where binaries land. Always /usr/local/bin in the image; overridable so the
# unit tests can exercise the installers without writing outside their tmpdir.
BIN_DIR="${TOOLS_BIN_DIR:-/usr/local/bin}"

if [ -n "${GITHUB_TOKEN:-}" ]; then
  AUTH_ARGS=(-H "Authorization: Bearer ${GITHUB_TOKEN}")
else
  AUTH_ARGS=()
fi

# api_get <url> — GET the GitHub API with retries; echo body (empty on failure).
api_get() {
  local url="$1" body="" i
  for i in 1 2 3; do
    body=$(curl -fsSL ${AUTH_ARGS[@]+"${AUTH_ARGS[@]}"} \
             -H "Accept: application/vnd.github+json" "$url") && [ -n "$body" ] && break
    [ "$i" -lt 3 ] && { echo "  API attempt $i failed, retrying in 5s..." >&2; sleep 5; }
  done
  printf '%s' "$body"
}

# asset_name <binary> <tag> — release asset filename for this OS/ARCH.
asset_name() { printf '%s_%s_%s_%s.tar.gz' "$1" "${2#v}" "$OS" "$ARCH"; }

# install_repo_file <name> <ref> — install a prebuilt binary COMMITTED IN the
# repo (install=repo-file), rather than published as a release asset.
#
# Used by tools whose artifacts are vendored into a git repo, so there is no
# release to resolve and nothing to untar: the file at repo_path IS the binary.
# repo_path may contain ${ARCH}, expanded to this image's amd64/arm64.
#
# <ref> is a branch/tag/commit, or "latest" for the repo's default branch. The
# contents API with the raw media type streams the file itself; for a private
# repo GITHUB_TOKEN is required (the private=yes guard in install_one covers it).
install_repo_file() {
  local name="$1" ref="$2"
  # shellcheck disable=SC2154
  local repo="$TOOL_repo" binary="$TOOL_binary" path="$TOOL_repo_path"

  if [ -z "$repo" ] || [ -z "$path" ]; then
    echo "WARNING: ${name} sets install=repo-file but repo= or repo_path= is empty — skipping." >&2
    return 0
  fi

  path="${path//\$\{ARCH\}/$ARCH}"
  path="${path//\$ARCH/$ARCH}"

  local url="https://api.github.com/repos/${repo}/contents/${path}"
  # "latest" means the default branch: send no ref and let GitHub decide.
  if [ "$ref" != "latest" ]; then
    url="${url}?ref=${ref}"
  elif [ -n "$TOOL_ref" ]; then
    url="${url}?ref=${TOOL_ref}"
  fi

  local dest="${BIN_DIR}/${binary}" tmp
  # mktemp, not a predictable name: /tmp is shared, and a pre-existing symlink at
  # a guessable path would otherwise be written through.
  if ! tmp="$(mktemp "${TMPDIR:-/tmp}/${binary}.XXXXXX")"; then
    echo "WARNING: could not create a temp file for ${name} — skipping." >&2
    return 0
  fi

  echo "Installing ${name} from ${repo}:${path}..."
  if ! curl -fsSL ${AUTH_ARGS[@]+"${AUTH_ARGS[@]}"} \
         -H "Accept: application/vnd.github.raw" "$url" -o "$tmp"; then
    echo "WARNING: download failed for ${name} (${repo}:${path}) — skipping." >&2
    echo "         Check the path exists on that ref and that GITHUB_TOKEN grants access." >&2
    rm -f "$tmp"
    return 0
  fi
  if [ ! -s "$tmp" ]; then
    echo "WARNING: ${name} downloaded empty — skipping." >&2
    rm -f "$tmp"
    return 0
  fi
  # The contents API answers a DIRECTORY path with 200 and a JSON listing, which
  # curl -f cannot distinguish from a file. Installing that as the binary would
  # "succeed" and only fail when the agent runs it.
  case "$(head -c 1 "$tmp")" in
    '['|'{')
      echo "WARNING: ${name}: the API returned JSON, not a file — is repo_path a directory?" >&2
      echo "         repo_path=${path}" >&2
      rm -f "$tmp"
      return 0
      ;;
  esac
  # Failures here are why this is checked: an unwritable BIN_DIR would otherwise
  # print "Installed" while nothing was installed.
  if ! mv "$tmp" "$dest" || ! chmod +x "$dest"; then
    echo "WARNING: could not install ${name} to ${dest} — skipping." >&2
    rm -f "$tmp"
    return 0
  fi
  echo "Installed ${name} (${repo}:${path})"
}

# parse_versions <str> — echo "name<TAB>version" per entry (pure; for tests/main).
parse_versions() {
  local IFS=';' entry name version _e
  read -ra _e <<< "$1"
  for entry in "${_e[@]}"; do
    [ -n "$entry" ] || continue
    name="${entry%%=*}"; version="${entry#*=}"
    printf '%s\t%s\n' "$name" "$version"
  done
}

install_one() {
  local name="$1" version="$2"
  tools_read_descriptor "$name" || { echo "WARNING: no descriptor for '$name' — skipping." >&2; return 0; }
  [ -n "$version" ] || return 0
  # TOOL_* are set by tools_read_descriptor in the sourced tools-lib.sh.
  # shellcheck disable=SC2154
  local private="$TOOL_private" repo="$TOOL_repo" binary="$TOOL_binary"

  if [ "$private" = "yes" ] && [ -z "${GITHUB_TOKEN:-}" ]; then
    {
      echo "════════════════════════════════════════════════════════════════"
      echo "WARNING: '$name' is a PRIVATE repo (${repo}) and requires GITHUB_TOKEN."
      echo "         No token provided — skipping ${name}."
      echo "         Set GITHUB_TOKEN on the host and rebuild: ./build.sh"
      echo "════════════════════════════════════════════════════════════════"
    } >&2
    return 0
  fi

  # A vendored binary (install=repo-file) is fetched straight from the repo tree;
  # there is no release to resolve and no archive to unpack.
  if [ "$TOOL_install" = "repo-file" ]; then
    install_repo_file "$name" "$version"
    return 0
  fi

  local tag an
  if [ "$private" = "yes" ]; then
    local api="https://api.github.com/repos/${repo}/releases" release_json
    if [ "$version" = "latest" ]; then release_json=$(api_get "${api}/latest")
    else release_json=$(api_get "${api}/tags/v${version#v}"); fi
    tag=$(printf '%s' "$release_json" | jq -r '.tag_name // empty')
    [ -n "$tag" ] || { echo "WARNING: could not resolve ${name} release — skipping." >&2; return 0; }
    an=$(asset_name "$binary" "$tag")
    local asset_id
    asset_id=$(printf '%s' "$release_json" | jq -r --arg n "$an" '.assets[] | select(.name==$n) | .id')
    [ -n "$asset_id" ] || { echo "WARNING: asset ${an} not found for ${name} ${tag} — skipping." >&2; return 0; }
    echo "Installing ${name} ${tag} (private)..."
    if ! curl -fsSL ${AUTH_ARGS[@]+"${AUTH_ARGS[@]}"} -H "Accept: application/octet-stream" \
           "https://api.github.com/repos/${repo}/releases/assets/${asset_id}" \
         | tar xz -C "$BIN_DIR" "$binary"; then
      echo "WARNING: download/extract failed for ${name} ${tag} — skipping." >&2; return 0
    fi
  else
    if [ "$version" = "latest" ]; then
      tag=$(printf '%s' "$(api_get "https://api.github.com/repos/${repo}/releases/latest")" \
              | jq -r '.tag_name // empty')
      if [ -z "$tag" ]; then
        echo "WARNING: could not resolve latest ${name} (rate limit?) — skipping." >&2
        echo "         Pin a version in sandbox.conf (e.g. ${name}=0.25.0) or set GITHUB_TOKEN." >&2
        return 0
      fi
    else
      tag="v${version#v}"
    fi
    an=$(asset_name "$binary" "$tag")
    echo "Installing ${name} ${tag}..."
    if ! curl -fsSL "https://github.com/${repo}/releases/download/${tag}/${an}" \
         | tar xz -C "$BIN_DIR" "$binary"; then
      echo "WARNING: download/extract failed for ${name} ${tag} — skipping." >&2
      echo "         Check that version '${tag#v}' exists at https://github.com/${repo}/releases" >&2
      return 0
    fi
  fi
  chmod +x "${BIN_DIR}/${binary}"
  echo "Installed ${name} ${tag}"
}

main() {
  local name version
  while IFS=$'\t' read -r name version; do
    install_one "$name" "$version"
  done < <(parse_versions "${TOOL_VERSIONS:-}")
}

# Execute only when run directly; allow sourcing for unit tests.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then main; fi
