#!/usr/bin/env bash
# link-default-ruby.sh — runs as ROOT at container start, AFTER rvm-reconcile.sh has
# installed and defaulted the per-user rvm. Symlinks the default Ruby's executables
# onto the global PATH (/usr/local/bin) so NON-interactive, NON-login shells resolve
# ruby/gem/bundle without sourcing rvm — e.g. `docker exec -T <ctr> bash -c "bin/rails …"`,
# which otherwise gets "command not found". (Login and interactive shells already source
# rvm via /etc/profile.d/rvm.sh and /etc/bash.bashrc; those paths are unaffected.)
#
# Scope: this exposes the DEFAULT Ruby only. Per-project gemset selection still comes
# from .ruby-version when a shell sources rvm; a non-interactive caller that needs the
# project gemset must go through a login shell. See rvm-home-in-group design §3e/§6.
#
# No `set -u`: keep parity with rvm-reconcile.sh and tolerate an unset RUBY_VERSIONS.
set -o pipefail

[[ -n "${RUBY_VERSIONS:-}" ]] || exit 0   # no Ruby configured → nothing to expose

dev_home="${1:-$HOME}"
bin_dest="${2:-/usr/local/bin}"   # override only for testing; entrypoint uses the default
rvm_root="$dev_home/.rvm"

log(){ printf '[link-default-ruby] %s\n' "$*"; }

# Resolve the default Ruby's bin dir. Prefer rvm's own 'default' alias symlink when the
# installed rvm creates it; otherwise fall back to the first requested version that is
# actually installed — which matches the default rvm-reconcile.sh selects (first present
# version, in requested order).
bindir=""
if [[ -d "$rvm_root/rubies/default/bin" ]]; then
  bindir="$rvm_root/rubies/default/bin"
else
  for v in ${RUBY_VERSIONS:-}; do
    if [[ -d "$rvm_root/rubies/ruby-$v/bin" ]]; then
      bindir="$rvm_root/rubies/ruby-$v/bin"
      break
    fi
  done
fi

if [[ -z "$bindir" ]]; then
  log "no installed Ruby found under $rvm_root/rubies; nothing to link"
  exit 0
fi

linked=""
for b in ruby gem bundle bundler rake irb erb; do
  if [[ -x "$bindir/$b" ]]; then
    ln -sf "$bindir/$b" "$bin_dest/$b"
    linked="${linked:+$linked }$b"
  fi
done
log "linked default Ruby from $bindir into $bin_dest: ${linked:-none}"

# rvm rewrites gem binstub shebangs to `#!/usr/bin/env ruby_executable_hooks` (the
# executable-hooks gem, installed into the @global gemset). A non-login shell has
# neither ~/.rvm/bin nor the gemset bin dir on PATH, so linking the binstub alone
# left `bundle` resolving but dying with
#   /usr/bin/env: 'ruby_executable_hooks': No such file or directory
# while plain `ruby`/`gem` (no rewritten shebang) worked — which is why this only
# showed up once the bootstrap itself started succeeding. Expose the hook too.
hook=""
for cand in "$rvm_root/bin/ruby_executable_hooks" "$rvm_root"/gems/*@global/bin/ruby_executable_hooks \
            "$rvm_root"/gems/*/bin/ruby_executable_hooks; do
  if [[ -x "$cand" ]]; then hook="$cand"; break; fi
done
if [[ -n "$hook" ]]; then
  ln -sf "$hook" "$bin_dest/ruby_executable_hooks"
  log "linked ruby_executable_hooks from $hook"
fi

# Verify each link actually RUNS, and fall back to rvm's own wrapper for any that
# does not. wrappers/<ruby>/ is generated by the gem-wrappers gem for precisely this
# case — each wrapper sets GEM_HOME/GEM_PATH/PATH and then execs — so it works
# without rvm being sourced, at the cost of a bash process per call. Preferring the
# direct binstub and falling back only on failure keeps the fast path fast and stops
# a silently broken `bundle` from reaching a caller.
wrapdir=""
for cand in "$rvm_root/wrappers/default" "$rvm_root"/wrappers/ruby-*; do
  if [[ -d "$cand" ]]; then wrapdir="$cand"; break; fi
done
if [[ -n "$wrapdir" ]]; then
  repaired=""
  for b in $linked; do
    "$bin_dest/$b" --version >/dev/null 2>&1 && continue
    if [[ -x "$wrapdir/$b" ]]; then
      ln -sf "$wrapdir/$b" "$bin_dest/$b"
      repaired="${repaired:+$repaired }$b"
    else
      log "WARNING: $b does not run and $wrapdir/$b is not available to fall back to"
    fi
  done
  [[ -n "$repaired" ]] && log "re-pointed at rvm wrappers (direct binstub would not run): $repaired"
fi
