#!/usr/bin/env bash
# migrate-runme.sh — non-interactively migrate old-style, fat project launchers
# (a runme.sh with export VAR=value lines baked in) to the current split:
# sandbox.env (portable) / sandbox.local.env (this machine) + a thin runme.sh.
#
# Exists because project-init.sh is interactive-only (read -r -p prompts), which
# makes re-running it across many already-configured projects, just to pick up a
# format change, expensive: you'd have to open each old runme.sh, copy its values
# by hand, and retype them into the wizard. This script parses those values
# straight out of the old runme.sh instead, and reuses project-init.sh's own
# emit_launcher() (sourced, not invoked — it returns early when sourced, see its
# own BASH_SOURCE guard) so the thin runme.sh it writes never drifts from what the
# wizard would produce.
#
# Usage:
#   ./migrate-runme.sh [--dry-run] [--projects-conf <path>] [<project-path> ...]
#
# With no positional paths, reads project paths from --projects-conf (default:
# this repo's own projects.conf). Pass --projects-conf to run it a second time
# against another repo's registry (e.g. a personal fork with its own
# project-init.sh/projects.conf) — emit_launcher()'s output doesn't depend on
# which repo a target project came from.
#
# A project is skipped (idempotent) if its runme.sh already matches the thin
# template. Before writing, existing sandbox.env / sandbox.local.env / runme.sh
# are copied to *.pre-migrate — the per-project .ai-containers/ tree is
# gitignored in its own repo, so these backups are the only safety net.
set -euo pipefail

own_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Sourcing (not executing) project-init.sh pulls in its helpers — emit_launcher,
# valid_group_name — and its own `script_dir`/`projects_conf` globals, without
# running the interactive wizard: project-init.sh returns early when sourced via
# a BASH_SOURCE guard. That guard and emit_launcher() are BOTH real now; this
# comment previously described both as existing when neither did, and every run
# of this script died at the source line with no output at all.
# shellcheck disable=SC1091
source "${own_dir}/project-init.sh"
default_projects_conf="$projects_conf"

dry_run=0
projects_conf_arg=""
paths=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) dry_run=1; shift ;;
    --projects-conf) projects_conf_arg="${2:-}"; shift 2 ;;
    --projects-conf=*) projects_conf_arg="${1#*=}"; shift ;;
    -h|--help)
      printf 'Usage: %s [--dry-run] [--projects-conf <path>] [<project-path> ...]\n' "$(basename "$0")"
      exit 0 ;;
    -*) printf 'ERROR: unknown argument: %s\n' "$1" >&2; exit 1 ;;
    *) paths+=("$1"); shift ;;
  esac
done

target_conf="${projects_conf_arg:-$default_projects_conf}"

if [[ ${#paths[@]} -eq 0 ]]; then
  [[ -f "$target_conf" ]] || { printf 'ERROR: no projects.conf at %s and no paths given\n' "$target_conf" >&2; exit 1; }
  while IFS= read -r line; do
    [[ -z "$line" || "$line" == \#* ]] && continue
    paths+=("$line")
  done < "$target_conf"
fi

count_migrated=0
count_skipped=0

# Extract every `export VAR=value` line from an old runme.sh into the global
# associative array `vals`. A bare `export GITHUB_TOKEN` (no `=`, from the
# gh-token bootstrap block every generation of runme.sh carries) never matches.
parse_exports() {
  local file="$1" line key val
  vals=()
  while IFS= read -r line; do
    [[ "$line" =~ ^export\ ([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]] || continue
    key="${BASH_REMATCH[1]}"
    val="${BASH_REMATCH[2]}"
    if [[ "$val" =~ ^\"(.*)\"$ ]]; then
      val="${BASH_REMATCH[1]}"
    elif [[ "$val" =~ ^\'(.*)\'$ ]]; then
      val="${BASH_REMATCH[1]}"
    else
      # Unquoted value: bash treats a whitespace-preceded '#' as a comment
      # start, not part of the value (e.g. "export FOO=bar # note").
      val="${val%% #*}"
    fi
    [[ -z "$val" ]] && continue
    vals["$key"]="$val"
  done < "$file"
}

# Extract the active (uncommented) ./build.sh and ./sandbox.sh invocation from
# an old runme.sh into the globals `build_nocache`, `mode`, `workdir`. A
# commented-out alternative (e.g. "#./sandbox.sh restricted @app") is ignored —
# regex anchors on '.' at line start, which a leading '#' never satisfies.
parse_invocation() {
  local file="$1" line
  build_nocache=0
  mode=""
  workdir=""
  while IFS= read -r line; do
    if [[ "$line" =~ ^\./build\.sh(\ +--no-cache)?\ *$ ]]; then
      [[ -n "${BASH_REMATCH[1]:-}" ]] && build_nocache=1
    elif [[ "$line" =~ ^\./sandbox\.sh(\ +([^\ ]+))?(\ +([^\ ]+))?\ *$ ]]; then
      mode="${BASH_REMATCH[2]:-}"
      workdir="${BASH_REMATCH[4]:-}"
    fi
  done < "$file"
}

process_project() {
  local project_path="$1"
  local dest="${project_path}/.ai-containers"
  local old_runme="${dest}/runme.sh"

  if [[ ! -f "$old_runme" ]]; then
    printf '  SKIP  %s — no .ai-containers/runme.sh\n' "$project_path"
    ((++count_skipped))
    return 0
  fi
  if grep -q 'Thin wrapper generated by' "$old_runme" 2>/dev/null; then
    printf '  SKIP  %s — runme.sh already thin\n' "$project_path"
    ((++count_skipped))
    return 0
  fi

  printf '\n=== %s ===\n' "$project_path"

  local -A vals
  local build_nocache mode workdir
  parse_exports "$old_runme"
  parse_invocation "$old_runme"

  local project_name image_name group_name container_cpus container_memory
  local container_memory_reservation container_memory_swap preview_ports
  local group_init extra_mounts repos

  project_name="$(basename "$project_path")"

  image_name="${vals[IMAGE_NAME]:-}"
  if [[ -z "$image_name" && -f "${dest}/sandbox.env" ]]; then
    image_name="$(grep -m1 '^IMAGE_NAME=' "${dest}/sandbox.env" 2>/dev/null | cut -d= -f2-)"
  fi
  image_name="${image_name:-${project_name}-ai-container}"

  group_name="${vals[AI_CONTAINER_GROUP]:-default}"
  if ! valid_group_name "$group_name"; then
    printf '  WARN: parsed AI_CONTAINER_GROUP=%s looks invalid — check sandbox.env after migration.\n' "$group_name"
  fi

  container_cpus="${vals[CONTAINER_CPUS]:-4.0}"
  container_memory="${vals[CONTAINER_MEMORY]:-8g}"
  container_memory_reservation="${vals[CONTAINER_MEMORY_RESERVATION]:-4g}"
  container_memory_swap="${vals[CONTAINER_MEMORY_SWAP]:-$container_memory}"
  preview_ports="${vals[PREVIEW_PORTS]:-}"

  group_init="${vals[AI_CONTAINER_GROUP_INIT]:-}"
  extra_mounts="${vals[EXTRA_MOUNTS]:-}"
  repos="${vals[REPOS]:-}"

  if [[ -z "$mode" ]]; then
    printf '  WARN: no active ./sandbox.sh call found — defaulting SANDBOX_MODE=open, SANDBOX_WORKDIR=%s. Verify after migration.\n' "$workdir"
    mode="open"
  fi

  printf '  IMAGE_NAME=%s  AI_CONTAINER_GROUP=%s\n' "$image_name" "$group_name"
  printf '  CPUS=%s  MEMORY=%s  RESERVATION=%s  SWAP=%s\n' "$container_cpus" "$container_memory" "$container_memory_reservation" "$container_memory_swap"
  printf '  SANDBOX_MODE=%s  SANDBOX_WORKDIR=%s  PREVIEW_PORTS=%s\n' "$mode" "$workdir" "$preview_ports"
  printf '  EXTRA_MOUNTS=%s\n  REPOS=%s\n  AI_CONTAINER_GROUP_INIT=%s\n' "$extra_mounts" "$repos" "$group_init"
  if (( build_nocache )); then
    printf '  NOTE: old runme.sh had --no-cache active on ./build.sh — not persisted (one-off flag, not launcher state). Run it manually once more if you still need a fresh pull: ./build.sh --no-cache\n'
  fi

  if (( dry_run )); then
    printf '  [dry-run] would write sandbox.env, sandbox.local.env (if applicable), and a thin runme.sh.\n'
    ((++count_migrated))
    return 0
  fi

  local f
  for f in "${dest}/sandbox.env" "${dest}/sandbox.local.env" "$old_runme"; do
    # Same no-clobber rule as project-init.sh's .pre-init backup: a second
    # migration of the same project must not overwrite the first backup, which
    # is the only copy of the original launcher.
    if [[ -f "$f" ]]; then
      bk="${f}.pre-migrate"
      [[ -e "$bk" ]] && bk="${f}.pre-migrate.$(date -u +%Y%m%dT%H%M%SZ)"
      cp "$f" "$bk"
    fi
  done

  {
    printf '# sandbox.env — PORTABLE launcher config for %s'"'"'s AI sandbox.\n' "$project_name"
    printf 'IMAGE_NAME=%s\n' "$image_name"
    printf 'AI_CONTAINER_GROUP=%s\n' "$group_name"
    printf 'CONTAINER_CPUS=%s\n' "$container_cpus"
    printf 'CONTAINER_MEMORY=%s\n' "$container_memory"
    printf 'CONTAINER_MEMORY_RESERVATION=%s\n' "$container_memory_reservation"
    printf 'CONTAINER_MEMORY_SWAP=%s\n' "$container_memory_swap"
    printf 'SANDBOX_MODE=%s\n' "$mode"
    printf 'SANDBOX_WORKDIR=%s\n' "$workdir"
    [[ -n "$preview_ports" ]] && printf 'PREVIEW_PORTS="%s"\n' "$preview_ports"
    cat <<'EOF'
# Machine-specific settings belong in sandbox.local.env (gitignored), NOT here:
#   EXTRA_MOUNTS="/abs/path /another:ro"   # host bind mounts (Linux-native; absolute paths)
#   REPOS="app:rw lib:ro"                  # named-volume repos (./repo.sh add; macOS perf)
#   SANDBOX_WORKDIR=@app                   # named-volume working dir (macOS)
EOF
  } > "${dest}/sandbox.env"

  if [[ -n "$extra_mounts" || -n "$group_init" || -n "$repos" ]]; then
    {
      cat <<'EOF'
# sandbox.local.env — THIS MACHINE's launcher config (gitignored, not shared).
# Overrides sandbox.env (loaded at higher precedence). Machine/platform-specific:
# absolute bind paths, named-volume repos, the group bootstrap, workdir/resource overrides.
EOF
      [[ -n "$group_init"   ]] && printf 'AI_CONTAINER_GROUP_INIT=%s\n' "$group_init"
      [[ -n "$extra_mounts" ]] && printf 'EXTRA_MOUNTS="%s"\n' "$extra_mounts"
      [[ -n "$repos"        ]] && printf 'REPOS="%s"\n' "$repos"
    } > "${dest}/sandbox.local.env"
  else
    rm -f "${dest}/sandbox.local.env"
  fi

  # emit_launcher <dest-path> <project-name>. This previously passed a single
  # argument to a function that did not exist at all — see the header note.
  emit_launcher "${dest}/runme.sh" "$project_name"

  printf '  Wrote sandbox.env, %s, and a thin runme.sh (old files backed up as *.pre-migrate).\n' \
    "$([[ -f "${dest}/sandbox.local.env" ]] && echo sandbox.local.env || echo '(no sandbox.local.env needed)')"
  ((++count_migrated))
}

for p in "${paths[@]}"; do
  process_project "$p" || printf '  ERROR processing %s — see message above.\n' "$p" >&2
done

printf '\nDone. Migrated: %d  Skipped: %d\n' "$count_migrated" "$count_skipped"
if (( dry_run )); then
  printf '(dry-run: nothing was written)\n'
fi
