#!/usr/bin/env bash
# project-init.sh — interactively configure a project to use ai-containers.
#
# Prompts for image name, project location, container group (with optional
# from-which-group bootstrap), CPU/memory limits, and extra mounts. Then
# copies the shared .ai-containers infrastructure into the project, registers
# it in projects.conf, and writes a ready-to-run runme.sh launcher modelled on
# ihudak-claude-plugins/.ai-containers/claude-plugins.sh.
#
# Most config vars (project_name, image_name, container_*, group_name, ...) are
# assigned indirectly via prompt_with_default's `printf -v "$varname"`. That
# indirect assignment is untraceable by the linter, which then reports them as
# referenced-but-unassigned; suppress that class file-wide (must precede the
# first command to apply to the whole file):
# shellcheck disable=SC2154
set -euo pipefail

# emit_launcher <path> <project-name> — write the thin runme.sh launcher.
#
# A FUNCTION, not an inline heredoc, because migrate-runme.sh sources this file
# to reuse it: one launcher template, two callers, no drift the next time the
# launcher changes. It previously WAS inline, and migrate-runme.sh called an
# emit_launcher() that had never existed — every run died at "command not found"
# (silently, because the source happened before its own argument parsing).
valid_group_name() {
  # Mirrors validate_group_name() in sandbox-common.sh.
  [[ "$1" =~ ^[a-z0-9][a-z0-9-]{0,31}$ ]]
}

emit_launcher() {  # $1=destination path  $2=project name
  local dest_path="$1" proj_name="$2"
  cat > "$dest_path" <<EOF
#!/usr/bin/env bash
# runme.sh — launch the AI sandbox for ${proj_name}. Thin wrapper generated by
# project-init.sh (re-run it to regenerate). Config lives in sandbox.env (portable) and
# sandbox.local.env (this machine); precedence inline > local > portable.
set -euo pipefail
cd "\$(dirname "\${BASH_SOURCE[0]}")"

# Build-time GitHub token for private tool downloads. build.sh passes it to docker build
# as a BuildKit secret; sandbox.sh does NOT forward it into the container. Non-clobbering
# (an already-set token wins), gh-optional (absence degrades to "no token").
if command -v gh >/dev/null 2>&1; then
  : "\${GITHUB_TOKEN:=\$(gh auth token 2>/dev/null || true)}"
  export GITHUB_TOKEN
fi

./build.sh
#./build.sh --no-cache

# Network mode + working dir come from SANDBOX_MODE / SANDBOX_WORKDIR (sandbox.env /
# sandbox.local.env). One-off override:  SANDBOX_MODE=restricted ./runme.sh
# Or drive sandbox.sh directly:           ./sandbox.sh restricted @app
./sandbox.sh
EOF
  chmod +x "$dest_path"
}


script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
projects_conf="${script_dir}/projects.conf"

# SOURCING GUARD — placed AFTER the globals above and BEFORE the first
# interactive prompt, deliberately. A sourcing caller (migrate-runme.sh) needs
# emit_launcher() *and* script_dir/projects_conf, but must not run the wizard:
# without this, `source project-init.sh` executed the whole thing as a side
# effect, rsyncing files and appending to projects.conf for whatever happened to
# be on stdin. Placing the guard any earlier leaves the caller with an unbound
# projects_conf; any later and the wizard has already started prompting.
# migrate-runme.sh's header already CLAIMED this guard existed.
if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
  return 0
fi


# ── Prompt helpers ─────────────────────────────────────────────────────────────

prompt_with_default() {
  # Usage: prompt_with_default "Question" "default" varname
  local q="$1" def="$2" varname="$3" reply
  if [[ -n "$def" ]]; then
    read -r -p "$q [$def]: " reply
    printf -v "$varname" '%s' "${reply:-$def}"
  else
    read -r -p "$q: " reply
    printf -v "$varname" '%s' "$reply"
  fi
}

# Expand a user-typed host path: leading ~ / ~user, and $VAR / ${VAR} references.
# read -r takes input literally, so bash never expands these on its own.
# Deliberately does NOT eval the input (no command substitution) — this only
# ever substitutes an existing shell variable's value, so a stray "$(...)" in
# a pasted path can't execute anything.
expand_path() {
  local p="$1"

  if [[ "$p" == "~" || "$p" == "~/"* ]]; then
    p="${HOME}${p:1}"
  elif [[ "$p" =~ ^~([^/]+)(.*)$ ]]; then
    local user="${BASH_REMATCH[1]}" rest="${BASH_REMATCH[2]}" userhome
    userhome="$(getent passwd "$user" 2>/dev/null | cut -d: -f6)"
    [[ -n "$userhome" ]] && p="${userhome}${rest}"
  fi

  local result="" rest="$p" var
  while [[ "$rest" =~ ^([^$]*)\$\{?([A-Za-z_][A-Za-z0-9_]*)\}?(.*)$ ]]; do
    var="${BASH_REMATCH[2]}"
    result+="${BASH_REMATCH[1]}${!var-}"
    rest="${BASH_REMATCH[3]}"
  done
  result+="$rest"

  printf '%s' "$result"
}

# Ensure the project's root .gitignore ignores its .ai-containers/ working copy.
# The per-project .ai-containers/ is a synced copy of the central repo and the
# launcher embeds machine-specific absolute paths (EXTRA_MOUNTS), so it should
# not be committed to the project. Idempotent, git-repos only; to keep it under
# version control instead (e.g. to share sandbox config with a team), remove the
# added line. Honour AI_CONTAINERS_NO_GITIGNORE=1 to skip entirely.
ensure_ai_containers_ignored() {
  local project_path="$1"
  [[ "${AI_CONTAINERS_NO_GITIGNORE:-0}" == "1" ]] && return 0
  git -C "$project_path" rev-parse --is-inside-work-tree >/dev/null 2>&1 || return 0
  git -C "$project_path" check-ignore -q .ai-containers 2>/dev/null && return 0
  local gi="${project_path}/.gitignore"
  # Guarantee a trailing newline before appending to an existing, non-empty file.
  if [[ -f "$gi" && -s "$gi" && -n "$(tail -c1 "$gi" 2>/dev/null)" ]]; then
    printf '\n' >> "$gi"
  fi
  {
    printf '# AI sandbox tooling — local working copy synced from the central ai-containers repo\n'
    printf '# (the launcher embeds machine-specific paths). Remove this line to version it instead.\n'
    printf '/.ai-containers/\n'
  } >> "$gi"
  printf '  Added /.ai-containers/ to %s/.gitignore\n' "$(basename "$project_path")"
}

# Parse a docker-style memory string (e.g. 512m, 2g, 1073741824, or -1) into bytes.
# Echoes the byte count (or "-1") and returns 0; returns 1 on parse failure.
mem_to_bytes() {
  local v="${1,,}"
  if [[ "$v" == "-1" ]]; then printf '%s' "-1"; return 0; fi
  if [[ "$v" =~ ^([0-9]+)([bkmg]?)$ ]]; then
    local num="${BASH_REMATCH[1]}" unit="${BASH_REMATCH[2]}"
    case "$unit" in
      b|"") printf '%s' "$num" ;;
      k)    printf '%s' "$(( num * 1024 ))" ;;
      m)    printf '%s' "$(( num * 1024 * 1024 ))" ;;
      g)    printf '%s' "$(( num * 1024 * 1024 * 1024 ))" ;;
    esac
    return 0
  fi
  return 1
}

# mem_le A B → true if both parse and A <= B.
mem_le() {
  local a b
  a="$(mem_to_bytes "$1")" || return 2
  b="$(mem_to_bytes "$2")" || return 2
  (( a <= b ))
}

# mem_ge A B → true if both parse and A >= B.
mem_ge() {
  local a b
  a="$(mem_to_bytes "$1")" || return 2
  b="$(mem_to_bytes "$2")" || return 2
  (( a >= b ))
}

# ── 1. Project path ────────────────────────────────────────────────────────────

while true; do
  prompt_with_default "Project path" "" project_path_input
  if [[ -z "$project_path_input" ]]; then
    printf '  Path is required.\n' >&2
    continue
  fi
  expanded_path="$(expand_path "$project_path_input")"
  if project_path="$(cd "$expanded_path" 2>/dev/null && pwd)"; then
    break
  fi
  printf '  ERROR: path does not exist: %s\n' "$expanded_path" >&2
done

# ── 2. Project name ────────────────────────────────────────────────────────────

default_name="$(basename "$project_path")"
prompt_with_default "Project name" "$default_name" project_name

# ── 3. Image name ──────────────────────────────────────────────────────────────

default_image="${project_name}-ai-container"
prompt_with_default "Image name" "$default_image" image_name

# ── 4. CPUs ────────────────────────────────────────────────────────────────────

prompt_with_default "Container CPUs" "4.0" container_cpus

# ── 5. Memory ──────────────────────────────────────────────────────────────────

prompt_with_default "Container memory (hard limit)" "8g" container_memory

# ── 5b. Memory reservation (soft limit, must be <= memory) ─────────────────────

while true; do
  prompt_with_default "Container memory reservation (soft limit, must be <= memory)" "4g" container_memory_reservation
  if mem_le "$container_memory_reservation" "$container_memory"; then
    break
  fi
  printf '  Reservation must be a valid memory value (e.g. 2g) and <= memory (%s). Got: %s\n' "$container_memory" "$container_memory_reservation" >&2
done

# ── 5c. Memory + swap total (must be >= memory, or -1 for unlimited) ───────────
# Recommended: equal to memory (disables swap) for predictable agent performance.

while true; do
  prompt_with_default "Container memory+swap total (>= memory; equal to memory disables swap; -1 = unlimited)" "$container_memory" container_memory_swap
  if [[ "$container_memory_swap" == "-1" ]] || mem_ge "$container_memory_swap" "$container_memory"; then
    break
  fi
  printf '  memory-swap must be a valid memory value >= memory (%s), or -1. Got: %s\n' "$container_memory" "$container_memory_swap" >&2
done

# ── 6. Group ───────────────────────────────────────────────────────────────────

while true; do
  prompt_with_default "Container group (AI_CONTAINER_GROUP)" "default" group_name
  if valid_group_name "$group_name"; then
    break
  fi
  printf '  Invalid group. Allowed: lowercase letters, digits, dashes; 1-32 chars; must start with alphanum.\n' >&2
done

# ── 7. Group init (conditional) ────────────────────────────────────────────────

group_init=""
group_root="$HOME/.ai-containers/$group_name"
if [[ "$group_name" != "host" && ! -d "$group_root" ]]; then
  printf "\nGroup '%s' does not exist yet. Initialize from:\n" "$group_name"

  init_values=()
  init_labels=()

  if [[ -d "$HOME/.ai-containers/default" && "$group_name" != "default" ]]; then
    init_values+=("from:default"); init_labels+=("default (recommended)")
  fi
  init_values+=("from:host"); init_labels+=("host (\$HOME)")

  if [[ -d "$HOME/.ai-containers" ]]; then
    while IFS= read -r dir; do
      [[ -z "$dir" ]] && continue
      name="$(basename "$dir")"
      [[ "$name" == "default" || "$name" == "$group_name" ]] && continue
      init_values+=("from:$name"); init_labels+=("$name")
    done < <(find "$HOME/.ai-containers" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sort)
  fi

  init_values+=("clean"); init_labels+=("<empty>")

  for i in "${!init_labels[@]}"; do
    printf '  %d) %s\n' "$((i+1))" "${init_labels[$i]}"
  done

  while true; do
    read -r -p "[1]: " reply
    [[ -z "$reply" ]] && reply=1
    if [[ "$reply" =~ ^[0-9]+$ ]] && (( reply >= 1 && reply <= ${#init_values[@]} )); then
      group_init="${init_values[$((reply-1))]}"
      break
    fi
    printf '  Invalid choice. Enter a number 1-%d.\n' "${#init_values[@]}" >&2
  done
fi

# ── 8. Extra mounts ────────────────────────────────────────────────────────────

prompt_with_default "Extra mounts (space-separated host paths, append :ro for read-only; empty to skip)" "" extra_mounts_input

# Expand ~ and $VARs in each mount now, so the launcher embeds resolved,
# machine-absolute paths regardless of how EXTRA_MOUNTS is later consumed.
extra_mounts=""
for token in $extra_mounts_input; do
  suffix="" path_part="$token"
  [[ "$token" == *:ro ]] && { suffix=":ro"; path_part="${token%:ro}"; }
  extra_mounts+="$(expand_path "$path_part")${suffix} "
done
extra_mounts="${extra_mounts% }"

# ── Copy shared files ──────────────────────────────────────────────────────────

dest="${project_path}/.ai-containers"
launch_script="${dest}/runme.sh"

printf '\nInitialising %s → %s\n' "$project_name" "$dest"
mkdir -p "$dest"

rsync -a --exclude='custom.txt' \
  "${script_dir}/allowlist-domains.d/"       "${dest}/allowlist-domains.d/"
rsync -a --exclude='custom.txt' \
  "${script_dir}/allowlist-proxy-domains.d/" "${dest}/allowlist-proxy-domains.d/"
rsync -a --exclude='custom.txt' \
  "${script_dir}/allowlist-cidrs.d/"         "${dest}/allowlist-cidrs.d/"
rsync -a "${script_dir}/tools.d/" "${dest}/tools.d/"

for f in Dockerfile Dockerfile.seed .dockerignore sandbox-common.sh build.sh sandbox.sh repo.sh entrypoint.sh \
          rvm-reconcile.sh link-default-ruby.sh agent-tools-reconcile.sh link-agent-tools.sh \
          refresh-ipset-allowlist.sh capture-blocked-traffic.sh \
          capture-agent-destinations.sh install-tools.sh install-agent-skills.sh tools-lib.sh; do
  [[ -f "${script_dir}/${f}" ]] && cp "${script_dir}/${f}" "${dest}/${f}"
done

if [[ ! -f "${dest}/sandbox.conf" ]]; then
  cp "${script_dir}/sandbox.conf" "${dest}/sandbox.conf"
  printf '  Copied sandbox.conf — edit it to choose components before building.\n'
else
  printf '  sandbox.conf already exists — skipping (not overwritten).\n'
fi

# Portable launcher config (tracked/shareable — same on any machine). Loaded by
# sandbox-common.sh so build.sh / sandbox.sh / repo.sh / the thin runme.sh all agree.
# Precedence: inline env > sandbox.local.env > sandbox.env. Not overwritten by sync.
{
  cat <<EOF
# sandbox.env — PORTABLE launcher config for ${project_name}'s AI sandbox.
IMAGE_NAME=${image_name}
AI_CONTAINER_GROUP=${group_name}
CONTAINER_CPUS=${container_cpus}
CONTAINER_MEMORY=${container_memory}
CONTAINER_MEMORY_RESERVATION=${container_memory_reservation}
CONTAINER_MEMORY_SWAP=${container_memory_swap}
SANDBOX_MODE=open
SANDBOX_WORKDIR=..
EOF
  cat <<'EOF'
# Machine-specific settings belong in sandbox.local.env (gitignored), NOT here:
#   EXTRA_MOUNTS="/abs/path /another:ro"   # host bind mounts (Linux-native; absolute paths)
#   REPOS="app:rw lib:ro"                  # named-volume repos (./repo.sh add; macOS perf)
#   SANDBOX_WORKDIR=@app                   # named-volume working dir (macOS)
EOF
} > "${dest}/sandbox.env"
printf '  Wrote sandbox.env (portable config).\n'

# Machine-specific config → sandbox.local.env (gitignored). Always written (even with
# no EXTRA_MOUNTS/group-init answered) so every project has a documented place for
# machine-local overrides. AI_CONTAINER_GROUP_INIT is a host-referential one-time
# group-bootstrap directive (e.g. from:host), so it belongs here, not in the shared
# portable file; EXTRA_MOUNTS holds this machine's absolute bind paths.
#
# Back up an existing file first: this write is unconditional, and unlike sandbox.env
# (whose values are all re-prompted), nothing here is ever re-asked — a hand-added
# REPOS=/SANDBOX_WORKDIR=@app/SANDBOX_MODE= would otherwise be silently lost.
if [[ -f "${dest}/sandbox.local.env" ]]; then
  cp "${dest}/sandbox.local.env" "${dest}/sandbox.local.env.pre-init"
  printf '  Backed up existing sandbox.local.env → sandbox.local.env.pre-init.\n'
fi
{
  cat <<'EOF'
# sandbox.local.env — THIS MACHINE's launcher config (gitignored, not shared).
# Overrides sandbox.env (loaded at higher precedence: inline env > sandbox.local.env > sandbox.env).
# Uncomment/add only what this machine or this one-off run needs:
#   EXTRA_MOUNTS="/abs/path /another:ro"   # host bind mounts (Linux-native; absolute paths)
#   REPOS="app:rw lib:ro"                  # named-volume repos (./repo.sh add; macOS perf)
#   SANDBOX_WORKDIR=@app                   # named-volume working dir (macOS)
#   AI_CONTAINER_GROUP_INIT=from:host      # one-time group bootstrap: clean|from:host|from:<group>
#
# SANDBOX_MODE overrides the portable default (currently "open" in sandbox.env). Options:
#   restricted  firewall enabled, NET_ADMIN/NET_RAW dropped from the agent shell
#   discovery   unrestricted egress + background pcap capture
#   open        unrestricted egress, no capture
#SANDBOX_MODE=open
EOF
  [[ -n "$group_init"   ]] && printf 'AI_CONTAINER_GROUP_INIT=%s\n' "$group_init"
  [[ -n "$extra_mounts" ]] && printf 'EXTRA_MOUNTS="%s"\n' "$extra_mounts"
} > "${dest}/sandbox.local.env"
printf '  Wrote sandbox.local.env (machine-specific).\n'

for dir in allowlist-domains.d allowlist-proxy-domains.d allowlist-cidrs.d; do
  custom="${dest}/${dir}/custom.txt"
  example="${dest}/${dir}/custom.txt.example"
  if [[ ! -f "$custom" && -f "$example" ]]; then
    cp "$example" "$custom"
    printf '  Created %s/%s/custom.txt from template.\n' "$(basename "$dest")" "$dir"
  fi
done

# Ensure the project's .ai-containers/.gitignore covers outputs + generated files.
gi="${dest}/.gitignore"
# Guarantee a trailing newline before appending to an existing, non-empty file
# (otherwise the first appended pattern gets glued onto the file's last line).
if [[ -f "$gi" && -s "$gi" && -n "$(tail -c1 "$gi" 2>/dev/null)" ]]; then
  printf '\n' >> "$gi"
fi
for pat in '.agent-blocked/' '.agent-discovery/' 'sandbox.local.env' 'sandbox.local.env.pre-init' \
           'allowlist-domains.txt' 'allowlist-proxy-domains.txt' 'allowlist-cidrs.txt' \
           'allowlist-domains.d/custom.txt' 'allowlist-proxy-domains.d/custom.txt' 'allowlist-cidrs.d/custom.txt'; do
  if [[ ! -f "$gi" ]] || ! grep -qxF "$pat" "$gi" 2>/dev/null; then
    printf '%s\n' "$pat" >> "$gi"
  fi
done
printf '  Ensured %s/.gitignore covers outputs and generated files.\n' "$(basename "$dest")"

# ── Write launcher ─────────────────────────────────────────────────────────────

write_launcher=1
if [[ -f "$launch_script" ]]; then
  read -r -p "  $(basename "$launch_script") already exists. Overwrite? [y/N]: " ow
  case "$ow" in
    y|Y|yes|YES) write_launcher=1 ;;
    *) write_launcher=0 ;;
  esac
fi

if (( write_launcher )); then
  emit_launcher "$launch_script" "$project_name"
  printf '  Wrote %s\n' "$(basename "$launch_script")"
else
  printf '  Kept existing %s.\n' "$(basename "$launch_script")"
fi

# Keep the project's .ai-containers/ working copy out of the project's own repo.
ensure_ai_containers_ignored "$project_path"

# ── Register project ───────────────────────────────────────────────────────────

if [[ ! -f "$projects_conf" ]]; then
  cp "${script_dir}/projects.conf.example" "$projects_conf"
  printf '  Created projects.conf from template.\n'
fi

if grep -qxF "$project_path" "$projects_conf" 2>/dev/null; then
  printf '  %s already registered in projects.conf.\n' "$project_path"
else
  printf '%s\n' "$project_path" >> "$projects_conf"
  printf '  Registered %s in projects.conf.\n' "$project_path"
fi

# ── Next steps ─────────────────────────────────────────────────────────────────

printf '\nDone. Next steps:\n'
printf '  1. (Optional) Edit %s to choose components.\n' "${dest}/sandbox.conf"
printf '  2. Run: %s\n' "$launch_script"
