#!/usr/bin/env bash
# Verifies migrate_launcher_naming's ONLY remaining job: idempotently repointing an
# existing launcher's stale ./runme.sh self-call to ./sandbox.sh. It must NEVER delete
# or rename anything.
#
# An earlier revision also auto-deleted any runme.sh lacking an `export IMAGE_NAME=`
# marker, on the theory that meant a stale pre-migration "engine" file — but the
# CURRENT thin runme.sh (see project-init.sh's launcher heredoc) never carries that
# marker either; only the now-retired "fat launcher" era did. That discriminator could
# no longer tell "current, correct" apart from "genuinely stale", and it silently
# deleted every real project's launcher the first time sync-to-projects.sh ran for
# real against them. This file's first case is that exact regression, pinned down.
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=portability.sh
source "$SCRIPT_DIR/tests/portability.sh"
# Source sync-to-projects.sh for its helpers without running a sync.
# shellcheck disable=SC1090
source "$SCRIPT_DIR/sync-to-projects.sh"

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
fail=0

# ── 1. A current-format (marker-less, thin-wrapper) runme.sh must survive untouched ──
dest1="$TMP/proj1/.ai-containers"; mkdir -p "$dest1"
cat > "$dest1/runme.sh" <<'EOF'
#!/usr/bin/env bash
# runme.sh — launch the AI sandbox for proj1. Thin wrapper generated by
# project-init.sh (re-run it to regenerate).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
./build.sh
./sandbox.sh
EOF
before1="$(p_sha1 "$dest1/runme.sh")"
migrate_launcher_naming "$dest1"
after1="$(p_sha1 "$dest1/runme.sh")"
[[ -f "$dest1/runme.sh" ]]        || { echo "FAIL: current-format runme.sh was deleted"; fail=1; }
[[ "$before1" == "$after1" ]]     || { echo "FAIL: current-format runme.sh was mutated"; fail=1; }

# ── 2. An existing launcher's stale ./runme.sh self-call is still repointed ──
dest2="$TMP/proj2/.ai-containers"; mkdir -p "$dest2"
printf '#!/usr/bin/env bash\nexport IMAGE_NAME=proj2-ai-container\n./runme.sh discovery ..\n' > "$dest2/runme.sh"
migrate_launcher_naming "$dest2"
grep -q './sandbox.sh' "$dest2/runme.sh" 2>/dev/null            || { echo "FAIL: stale ./runme.sh self-call not repointed"; fail=1; }
! grep -q '\./runme\.sh discovery' "$dest2/runme.sh" 2>/dev/null || { echo "FAIL: old self-call string still present"; fail=1; }

# Idempotency: a second run must not change anything further.
before2="$(p_sha1 "$dest2/runme.sh")"
migrate_launcher_naming "$dest2"
after2="$(p_sha1 "$dest2/runme.sh")"
[[ "$before2" == "$after2" ]] || { echo "FAIL: second run mutated an already-repointed launcher"; fail=1; }

# ── 3. Genuinely old artifacts (pre-fat-launcher engine + legacy container.sh) are ──
# left alone now — recovering those is project-init.sh's job (its interactive
# overwrite prompt), not a silent background delete/rename in sync.
dest3="$TMP/proj3/.ai-containers"; mkdir -p "$dest3"
printf '#!/usr/bin/env bash\n# old engine\necho engine\n' > "$dest3/runme.sh"
printf '#!/usr/bin/env bash\nexport IMAGE_NAME=proj3-ai-container\n./runme.sh discovery ..\n' > "$dest3/proj3-container.sh"
migrate_launcher_naming "$dest3"
[[ -f "$dest3/runme.sh" ]]           || { echo "FAIL: runme.sh was deleted"; fail=1; }
[[ -f "$dest3/proj3-container.sh" ]] || { echo "FAIL: legacy container.sh was deleted/renamed"; fail=1; }

(( fail == 0 )) && echo "PASS: launcher migration (repoint-only, never deletes or renames)" || exit 1
