#!/usr/bin/env bash
# Tests that capture-blocked-traffic.sh actually STARTS — the daemon that gives
# restricted mode its only record of what the firewall dropped.
#
# The bug this pins: the script runs `set -euo pipefail`, and its allowlist-cache
# build used `grep -v '^\s*#' F | grep -v '^\s*$' | sed …`. When F has no
# non-comment, non-blank line the second grep exits 1, pipefail propagates, and
# `set -e` killed the whole daemon ~150 lines before init_output_files. Nothing was
# logged: no blocked.log, no blocked-domains.txt, no NFLOG watcher, and — worst —
# no SELF-HEALING, so dynamic CDN IPs behind an allowlisted wildcard silently
# stopped being admitted. An empty allowlist is a legal configuration:
# allowlist-proxy-domains.txt is nothing but its two header comments whenever no
# proxy-fragment component is enabled, which is why this was invisible to anyone
# running with copilot/claude-code ON.
#
# Hermetic: fake tshark/ipset on PATH, temp capture + internal dirs, no root.
set -uo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fails=0
pass() { printf 'PASS: %s\n' "$1"; }
fail() { printf 'FAIL: %s\n' "$1"; fails=$((fails + 1)); }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

bash -n "$REPO_DIR/capture-blocked-traffic.sh" \
  && pass "capture-blocked-traffic.sh bash -n" || fail "capture-blocked-traffic.sh bash -n"

FAKE_BIN="$TMP/bin"; mkdir -p "$FAKE_BIN"
# tshark must exit immediately so the two background watchers do not outlive the
# test; the script itself does not wait on them.
printf '#!/usr/bin/env bash\nexit 0\n' > "$FAKE_BIN/tshark"; chmod +x "$FAKE_BIN/tshark"
printf '#!/usr/bin/env bash\nexit 0\n' > "$FAKE_BIN/ipset";  chmod +x "$FAKE_BIN/ipset"

# Drive the real script to completion and report whether it survived to the point
# where it creates its output files and announces itself.
run_capture() {   # $1 = domains file, $2 = proxy-domains file
  local cap="$TMP/cap.$RANDOM" internal="$TMP/int.$RANDOM"
  mkdir -p "$cap" "$internal"
  local out rc
  out="$(PATH="$FAKE_BIN:$PATH" \
      BLOCKED_INTERNAL_DIR="$internal" \
      ALLOWLIST_DOMAINS_FILE="$1" \
      ALLOWLIST_PROXY_DOMAINS_FILE="$2" \
      bash "$REPO_DIR/capture-blocked-traffic.sh" "$cap" 2>&1)"
  rc=$?
  printf '%s\n---RC---\n%s\n---DIR---\n%s\n' "$out" "$rc" "$cap"
}

# ── The regression: comments-only allowlists ────────────────────────────────────
comments_only="$TMP/proxy-comments-only.txt"
printf '# AUTO-GENERATED by build.sh — do not edit directly.\n# Edit files in allowlist-proxy-domains.d/ and run: ./build.sh\n\n' \
  > "$comments_only"
populated="$TMP/domains.txt"
printf '# header\n  github.com  \n\nregistry.npmjs.org\n' > "$populated"

res="$(run_capture "$populated" "$comments_only")"
rc="$(printf '%s' "$res" | sed -n '/---RC---/{n;p;}')"
capdir="$(printf '%s' "$res" | sed -n '/---DIR---/{n;p;}')"

[[ "$rc" == "0" ]] \
  && pass "survives a comments-only proxy-domains file (exit 0)" \
  || fail "survives a comments-only proxy-domains file (exit $rc)"
printf '%s' "$res" | grep -q 'Blocked traffic capture started' \
  && pass "announces itself (reached the end of startup)" \
  || fail "announces itself (reached the end of startup) — got: $res"
for f in blocked.log blocked-domains.txt blocked-ips.txt; do
  [[ -f "$capdir/$f" ]] \
    && pass "init_output_files created $f" \
    || fail "init_output_files created $f"
done

# ── Both files comments-only — the most degenerate legal config ─────────────────
res2="$(run_capture "$comments_only" "$comments_only")"
rc2="$(printf '%s' "$res2" | sed -n '/---RC---/{n;p;}')"
[[ "$rc2" == "0" ]] \
  && pass "survives when BOTH allowlists are comments-only" \
  || fail "survives when BOTH allowlists are comments-only (exit $rc2)"

# ── A missing file must still be tolerated ──────────────────────────────────────
res3="$(run_capture "$populated" "$TMP/does-not-exist.txt")"
rc3="$(printf '%s' "$res3" | sed -n '/---RC---/{n;p;}')"
[[ "$rc3" == "0" ]] \
  && pass "survives a missing proxy-domains file" \
  || fail "survives a missing proxy-domains file (exit $rc3)"

# ── The cache content itself must be unchanged by the awk rewrite ───────────────
cache_internal="$TMP/cache-int"; cache_dir="$TMP/cache-cap"
mkdir -p "$cache_internal" "$cache_dir"
mixed="$TMP/mixed.txt"
printf '# comment\n  spaced.example.com  \n\n*.wild.example.com\n\t# indented comment\n' > "$mixed"
PATH="$FAKE_BIN:$PATH" BLOCKED_INTERNAL_DIR="$cache_internal" \
  ALLOWLIST_DOMAINS_FILE="$mixed" ALLOWLIST_PROXY_DOMAINS_FILE="$mixed" \
  bash "$REPO_DIR/capture-blocked-traffic.sh" "$cache_dir" >/dev/null 2>&1
got="$(tr '\n' '|' < "$cache_internal/allowed-domains-cache" 2>/dev/null)"
[[ "$got" == "spaced.example.com|*.wild.example.com|" ]] \
  && pass "cache still strips comments/blanks and trims whitespace" \
  || fail "cache still strips comments/blanks and trims whitespace (got '$got')"

# ── Regression guard on the construct itself ────────────────────────────────────
# Any `grep … | grep …` here is one empty allowlist away from killing the daemon
# again. Comments are stripped first so prose describing the old pipeline is fine.
if grep -vE '^[[:space:]]*#' "$REPO_DIR/capture-blocked-traffic.sh" \
     | grep -qE 'grep[^|]*\|[[:space:]]*grep'; then
  fail "allowlist parsing must not use a grep|grep pipeline under set -e"
else
  pass "allowlist parsing uses no fail-prone grep|grep pipeline"
fi

printf '\n%d failure(s)\n' "$fails"
exit "$fails"
